Repository finos/legend-studio, pull requests merged in 2021-11, with the labels that each got.

#629 Input to ServiceTestAssertLambda is updated to regular string
  .changeset/little-turkeys-hammer.md
  packages/legend-studio/src/stores/editor-state/element-editor-state/service/ServiceTestState.ts
Labels: cla-present

#632 Add viewer for workflow jobs and ability to cancel/rerun and view job logs
  .changeset/coffee-morning-sunshine.md
  .changeset/orange-apricots-refuse.md
  packages/legend-server-sdlc/src/SDLCServerClient.ts
  packages/legend-server-sdlc/src/index.ts
  packages/legend-studio/src/components/editor/side-bar/WorkspaceWorkflows.tsx
  packages/legend-studio/src/stores/sidebar-state/WorkspaceWorkflowsState.ts
  packages/legend-studio/style/components/editor/side-bar/_workspace-workflows.scss
Labels: cla-present

#595 Add form support for `Binding` and `ExternalFormatConnection`
  .changeset/lucky-moons-rest.md
  .changeset/rotten-rivers-sort.md
  packages/legend-extension-dsl-serializer/package.json
  packages/legend-extension-dsl-serializer/src/components/studio/BindingElementEditor.tsx
  packages/legend-extension-dsl-serializer/src/components/studio/DSLSerializer_StudioPlugin.tsx
  packages/legend-extension-dsl-serializer/src/components/studio/ExternalFormatConnectionEditor.tsx
  packages/legend-extension-dsl-serializer/src/index.ts
  packages/legend-extension-dsl-serializer/src/models/__tests__/TEST_DATA__DSLSerializer_Roundtrip.ts
  packages/legend-extension-dsl-serializer/src/models/metamodels/pure/model/packageableElements/store/Binding.ts
  packages/legend-extension-dsl-serializer/src/models/metamodels/pure/model/packageableElements/store/ModelUnit.ts
  packages/legend-extension-dsl-serializer/src/models/protocols/pure/DSLSerializer_PureProtocolProcessorPlugin.ts
  packages/legend-extension-dsl-serializer/src/stores/studio/BindingEditorState.ts
  packages/legend-extension-dsl-serializer/style/_mixins.scss
  packages/legend-extension-dsl-serializer/style/_serializer.scss
  packages/legend-extension-external-store-service/src/models/__tests__/TEST_DATA__ESService_Roundtrip.ts
  packages/legend-extension-external-store-service/src/models/metamodels/pure/model/packageableElements/store/serviceStore/model/TypeReference.ts
  packages/legend-extension-external-store-service/src/models/protocols/pure/v1/transformation/pureGraph/V1_ESService_GraphBuilderHelper.ts
  packages/legend-extension-external-store-service/src/models/protocols/pure/v1/transformation/pureGraph/V1_ESService_TransformerHelper.ts
  packages/legend-studio/src/components/editor/edit-panel/RuntimeEditor.tsx
  packages/legend-studio/src/index.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts
  yarn.lock
Labels: cla-present

#639 allow accessing Studio viewer mode using groupId, artifactId, and versionId (GAV coordinates)
  .changeset/brave-cows-sort.md
  .changeset/early-turkeys-press.md
  .changeset/gorgeous-poets-pretend.md
  .changeset/heavy-cooks-pump.md
  .changeset/little-turkeys-hammer.md
  .changeset/nine-snakes-tell.md
  .changeset/warm-forks-clap.md
  .changeset/weak-crews-doubt.md
  .github/ISSUE_TEMPLATE/Feature_request.yml
  packages/legend-application/package.json
  packages/legend-application/src/components/WebApplicationNavigatorProvider.tsx
  packages/legend-art/src/components/Icon.tsx
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/src/components/query/DataSpaceQuerySetup.tsx
  packages/legend-extension-dsl-data-space/src/components/query/DataSpaceViewer.tsx
  packages/legend-extension-dsl-data-space/src/stores/query/DataSpaceQuerySetupState.ts
  packages/legend-extension-dsl-data-space/style/_data-space-query-plugin.scss
  packages/legend-graph/src/models/metamodels/pure/packageableElements/mapping/SetImplementation.ts
  packages/legend-graph/src/models/protocols/pure/v1/model/packageableElements/mapping/V1_ClassMapping.ts
  packages/legend-query-app/scripts/setup.js
  packages/legend-query/package.json
  packages/legend-query/src/application/QueryConfig.ts
  packages/legend-query/src/components/QueryEditor.tsx
  packages/legend-query/src/stores/QueryBuilderState.ts
  packages/legend-query/src/stores/QueryStore.ts
  packages/legend-query/src/stores/QueryStoreTestUtils.ts
  packages/legend-query/style/_query-editor.scss
  packages/legend-server-depot/src/DepotUtils.ts
  packages/legend-server-depot/src/index.ts
  packages/legend-server-depot/src/models/ProjectData.ts
  packages/legend-server-depot/src/models/ProjectVersionEntities.ts
  packages/legend-studio/package.json
  packages/legend-studio/src/components/LegendStudioApplication.tsx
  packages/legend-studio/src/components/editor/edit-panel/mapping-editor/ClassMappingEditor.tsx
  packages/legend-studio/src/components/editor/side-bar/Explorer.tsx
  packages/legend-studio/src/components/viewer/Viewer.tsx
  packages/legend-studio/src/stores/EditorGraphState.ts
  packages/legend-studio/src/stores/LegendStudioRouter.ts
  packages/legend-studio/src/stores/ViewerStore.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingEditorState.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/service/ServiceExecutionState.ts
  yarn.lock
Labels: cla-present

#641 fix property references building in xstore property mapping
  .changeset/bottle-phone-watch.md
  .changeset/shaggy-geese-lay.md
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_ProtocolToMetaModelPropertyMappingBuilder.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/RoundtripGrammar.test.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/xstore-mapping.pure
Labels: cla-present

#646 Fix class explorer not showing properties from a class mapped using an operational set implementation
  .changeset/odd-donkeys-dance.md
  packages/legend-query/src/stores/QueryBuilderExplorerState.ts
Labels: cla-present

#653 Enterprise model explorer
  .changeset/angry-drinks-cheat.md
  .changeset/rude-dolphins-think.md
  .changeset/ten-sloths-bow.md
  docs/workflow/collaborator-responsibilities.md
  package.json
  packages/babel-preset/package.json
  packages/eslint-plugin/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-art/src/components/Icon.tsx
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-data-space/src/components/DataSpaceViewer.tsx
  packages/legend-extension-dsl-data-space/src/components/query/DataSpaceQuerySetup.tsx
  packages/legend-extension-dsl-data-space/src/components/studio/DSLDataSpace_StudioPlugin.tsx
  packages/legend-extension-dsl-data-space/src/components/studio/EnterpriseModelExplorer.tsx
  packages/legend-extension-dsl-data-space/src/components/studio/EnterpriseModelExplorerStoreProvider.tsx
  packages/legend-extension-dsl-data-space/src/components/studio/TaxonomyTree.tsx
  packages/legend-extension-dsl-data-space/src/components/studio/TaxonomyViewer.tsx
  packages/legend-extension-dsl-data-space/src/models/protocols/pure/DSLDataSpace_PureProtocolProcessorPlugin.ts
  packages/legend-extension-dsl-data-space/src/stores/DataSpaceViewerState.ts
  packages/legend-extension-dsl-data-space/src/stores/query/DataSpaceQuerySetupState.ts
  packages/legend-extension-dsl-data-space/src/stores/studio/EnterpriseModelExplorerStore.tsx
  packages/legend-extension-dsl-data-space/style/_data-space-query-plugin.scss
  packages/legend-extension-dsl-data-space/style/_data-space-viewer.scss
  packages/legend-extension-dsl-data-space/style/_enterprise-model-explorer.scss
  packages/legend-extension-dsl-data-space/style/_mixins.scss
  packages/legend-extension-dsl-data-space/style/index.scss
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-serializer/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-external-format-json-schema/package.json
  packages/legend-extension-external-store-service/package.json
  packages/legend-graph/package.json
  packages/legend-manual-tests/package.json
  packages/legend-model-storage/package.json
  packages/legend-query-app/package.json
  packages/legend-query-deployment/package.json
  packages/legend-query/package.json
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-studio-app/package.json
  packages/legend-studio-deployment/package.json
  packages/legend-studio-extension-management-toolkit/package.json
  packages/legend-studio-extension-query-builder/package.json
  packages/legend-studio/package.json
  packages/legend-studio/src/components/editor/edit-panel/mapping-editor/execution-plan-viewer/ExecutionPlanViewer.tsx
  packages/legend-studio/src/components/editor/side-bar/SideBar.tsx
  packages/legend-studio/src/components/review/Review.tsx
  packages/legend-studio/src/components/viewer/Viewer.tsx
  packages/legend-studio/style/components/editor/_side-bar.scss
  packages/legend-tracer-extension-zipkin/package.json
  packages/stylelint-config/package.json
  yarn.lock
Labels: cla-present

#657 minor cleanups
  .changeset/weak-horses-reply.md
  .github/workflows/bot-new-issue-label.yml
  .github/workflows/manual-docker-publish.yml
  .github/workflows/manual-npm-snapshot-publish.yml
  .github/workflows/manual-release-prepare.yml
  .github/workflows/manual-tests.yml
  docs/workflow/collaborator-responsibilities.md
  docs/workflow/release-process.md
  package.json
  packages/eslint-plugin/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-serializer/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-external-store-service/package.json
  packages/legend-query/package.json
  packages/legend-studio/package.json
  yarn.lock
Labels: cla-present

#645 Fix a bug with relational mapping tests set with the incorrect database
  .changeset/tender-foxes-battle.md
  packages/legend-studio/src/components/editor/edit-panel/mapping-editor/InstanceSetImplementationEditor.tsx
  packages/legend-studio/src/components/editor/edit-panel/mapping-editor/InstanceSetImplementationSourceSelectorModal.tsx
  packages/legend-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingEditorState.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingExecutionState.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingTestState.ts
Labels: cla-present

#654 Add extension mechanism for `class mapping` decorators
  .changeset/blue-jars-perform.md
  .changeset/flat-lies-train.md
  packages/legend-extension-dsl-serializer/src/components/studio/DSLSerializer_StudioPlugin.tsx
  packages/legend-extension-external-store-service/src/components/ESService_StudioPlugin.tsx
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/RoundtripGrammar.test.ts
  packages/legend-studio/src/components/editor/edit-panel/mapping-editor/EnumerationMappingEditor.tsx
  packages/legend-studio/src/components/editor/edit-panel/mapping-editor/InstanceSetImplementationEditor.tsx
  packages/legend-studio/src/components/editor/edit-panel/mapping-editor/InstanceSetImplementationSourceSelectorModal.tsx
  packages/legend-studio/src/components/editor/edit-panel/mapping-editor/MappingExecutionBuilder.tsx
  packages/legend-studio/src/components/editor/edit-panel/mapping-editor/MappingExplorer.tsx
  packages/legend-studio/src/components/editor/edit-panel/mapping-editor/MappingTestEditor.tsx
  packages/legend-studio/src/components/editor/edit-panel/mapping-editor/OperationSetImplementationEditor.tsx
  packages/legend-studio/src/stores/DSLMapping_StudioPlugin_Extension.ts
  packages/legend-studio/src/stores/NewElementState.tsx
  packages/legend-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/FlatDataInstanceSetImplementationState.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingEditorState.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingElementDecorator.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingExecutionState.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/PureInstanceSetImplementationState.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/relational/RelationalInstanceSetImplementationState.ts
  packages/legend-studio/src/stores/editor-state/element-editor-state/service/ServiceExecutionState.ts
Labels: cla-present

#661 Add form support for Snowflake proxy
  .changeset/loud-crews-sip.md
  packages/legend-studio/src/components/editor/edit-panel/connection-editor/RelationalDatabaseConnectionEditor.tsx
Labels: cla-present

#652 Properly resolve property mappings for inline/otherwise set implementations
  .changeset/cookie-monster-test.md
  .changeset/plenty-seahorses-build.md
  packages/legend-graph/src/GraphManagerState.ts
  packages/legend-query/src/components/QueryBuilderExplorerPanel.tsx
  packages/legend-query/src/components/__tests__/QueryBuilder_FetchStructure.test.tsx
  packages/legend-query/src/stores/QueryBuilderExplorerState.ts
  packages/legend-query/src/stores/QueryBuilderProjectionState.ts
  packages/legend-query/src/stores/__tests__/QueryBuilder_ExplorerState.test.ts
  packages/legend-query/src/stores/__tests__/TEST_DATA__Expected_MappingData.ts
  packages/legend-query/src/stores/__tests__/TEST_DATA__MappingData.ts
Labels: cla-present

#662 fix processing of include enum mapping
  .changeset/metal-lies-poke.md
  .changeset/testing-packages-deli.md
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_ProtocolToMetaModelClassMappingSecondPassBuilder.ts
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/to/V1_ProtocolToMetaModelPropertyMappingBuilder.ts
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/to/helpers/V1_AssociationMappingHelper.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/RoundtripGrammar.test.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/mapping-include-enum-mapping.pure
  packages/legend-studio/src/stores/editor-state/element-editor-state/mapping/MappingEditorState.ts
Labels: cla-present

#665 improve sass building workflow and optimize bot script
  .changeset/chilly-olives-drum.md
  .changeset/good-snails-collect.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/bot-new-issue-label.yml
  CONTRIBUTING.md
  package.json
  packages/legend-application/_package.config.js
  packages/legend-application/package.json
  packages/legend-art/_package.config.js
  packages/legend-art/package.json
  packages/legend-dev-utils/CopyrightUtils.js
  packages/legend-dev-utils/DevUtils.js
  packages/legend-extension-dsl-data-space/_package.config.js
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/_package.config.js
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-serializer/_package.config.js
  packages/legend-extension-dsl-serializer/package.json
  packages/legend-extension-dsl-text/_package.config.js
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-external-format-json-schema/_package.config.js
  packages/legend-extension-external-store-service/_package.config.js
  packages/legend-graph/_package.config.js
  packages/legend-query-app/_package.config.js
  packages/legend-query-app/package.json
  packages/legend-query-deployment/package.json
  packages/legend-query/_package.config.js
  packages/legend-query/package.json
  packages/legend-server-depot/_package.config.js
  packages/legend-server-sdlc/_package.config.js
  packages/legend-studio-app/_package.config.js
  packages/legend-studio-app/package.json
  packages/legend-studio-deployment/package.json
  packages/legend-studio-extension-management-toolkit/_package.config.js
  packages/legend-studio-extension-management-toolkit/package.json
  packages/legend-studio-extension-query-builder/_package.config.js
  packages/legend-studio-extension-query-builder/package.json
  packages/legend-studio/_package.config.js
  packages/legend-studio/package.json
  scripts/copyright/addBundledCodeCopyrightHeader.js
  scripts/github-bot/README.md
  scripts/github-bot/labelNewIssue.js
  scripts/github-bot/package.json
  scripts/github-bot/yarn.lock
  scripts/release/preparePublishContent.js
  scripts/workflow/buildSass.js
  scripts/workflow/devSassAll.js
  yarn.lock
Labels: cla-present, Type: Enhancement, Type: Maintenance

#666 cleanup and improve changeset config
  .changeset/chilly-olives-drum.md
  .changeset/config.json
  package.json
  scripts/release/releaseVersionUtils.js
  yarn.lock
Labels: cla-present

#669 update changeset
  .changeset/chilly-olives-drum.md
Labels: cla-present

#670 fix changeset
  .changeset/many-llamas-teach.md
Labels: cla-present

#672 fix add label script
  .github/workflows/bot-new-issue-label.yml
Labels: cla-present

#674 fix add label script
  .github/workflows/bot-new-issue-label.yml
Labels: cla-present

#676 fix new issue label github action
  .github/workflows/bot-new-issue-label.yml
  scripts/github-bot/README.md
Labels: cla-present

#678 fix changeset detection script
  .changeset/proud-countries-obey.md
  packages/legend-dev-utils/ChangesetUtils.js
  scripts/github-bot/README.md
Labels: cla-present

#663 Fix bug in filegeneration editor not resetting while changing elements
  .changeset/clever-seas-study.md
  packages/legend-studio/src/stores/editor-state/FileGenerationState.ts
Labels: cla-present

#681 Reveal simple compilation errors in m2m mapping in form mode properly
  .changeset/selfish-rockets-explain.md
  packages/legend-graph/src/graphManager/action/SourceInformationHelper.ts
Labels: cla-present

#696 Fix transformer for LatestDate
  .changeset/fuzzy-waves-vanish.md
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_ValueSpecificationTransformer.ts
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/to/__tests__/V1_TEST_DATA__ValueSpecificationBuilder.ts
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/to/__tests__/V1_ValueSpecificationBuilder.test.ts
Labels: cla-present

#693 Fix processing of `GraphFetchTree` with derived properties.
  .changeset/blue-tomatoes-peel.md
  .changeset/button-coffee-bottle.md
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/to/helpers/V1_DomainBuilderHelper.ts
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/to/helpers/V1_ValueSpecificationBuilderHelper.ts
  packages/legend-query/src/stores/__tests__/QueryBuilder_BuildLambdaRoundtrip.test.tsx
  packages/legend-query/src/stores/__tests__/QueryBuilder_LambdaProcessingRoundtrip.test.ts
  packages/legend-query/src/stores/__tests__/TEST_DATA__Expected_MappingData.ts
  packages/legend-query/src/stores/__tests__/TEST_DATA__QueryBuilder_Generic.ts
  packages/legend-query/src/stores/__tests__/TEST_DATA__QueryBuilder_LambdaProcessingRoundtrip.ts
  packages/legend-query/src/stores/__tests__/TEST_DATA__QueryBuilder_Model_ComplexM2M.json
Labels: cla-present

#700 Fix rendering generated file with no content in file generation editor
  .changeset/sixty-countries-bow.md
  packages/legend-studio/src/stores/editor-state/FileGenerationViewerState.ts
Labels: cla-present, Type: Bug

#701 Fetch depot projects for dependencies only in dependency tab in the config editor
  .changeset/slow-waves-brake.md
  packages/legend-studio/src/components/editor/edit-panel/__tests__/ProjectConfigurationEditor.test.tsx
  packages/legend-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectConfigurationEditor.tsx
  packages/legend-studio/src/stores/editor-state/ProjectConfigurationEditorState.ts
Labels: cla-present, Type: Bug

#703 use TEMP__useLegacyDepotServerAPIRoutes flag in Legend Taxonomy
  .changeset/proud-ants-rescue.md
  packages/legend-taxonomy/src/components/LegendTaxonomyApplication.tsx
Labels: cla-present

#695 Refactor reset states of QueryBuilder
  .changeset/little-boxes-laugh.md
  .changeset/spotty-cows-rush.md
  packages/legend-query/src/components/QueryBuilderFetchStructurePanel.tsx
  packages/legend-query/src/components/QueryBuilderSetupPanel.tsx
  packages/legend-query/src/components/__tests__/QueryBuilder_FetchStructure.test.tsx
  packages/legend-query/src/stores/LegendQueryStore.ts
  packages/legend-query/src/stores/QueryBuilderState.ts
  packages/legend-studio-extension-query-builder/src/components/QueryBuilder_LegendStudioPlugin.tsx
Labels: cla-present

#706 sort workflow jobs by creation date
  .changeset/pink-ties-drive.md
  .changeset/test-none-one.md
  packages/legend-server-sdlc/src/SDLCServerClient.ts
  packages/legend-studio/src/stores/sidebar-state/WorkspaceWorkflowsState.ts
Labels: cla-present

#710 query: auto-detect generic type while processing collection value specification
  .changeset/hip-peas-buy.md
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/to/helpers/V1_ValueSpecificationBuilderHelper.ts
Labels: cla-present

#712 Add support for role in Snowflake connection
  .changeset/blue-gifts-leave.md
  .changeset/two-months-deny.md
  packages/legend-graph/src/__tests__/roundtripTestData/TEST_DATA__RelationalRoundtrip.ts
  packages/legend-graph/src/models/metamodels/pure/packageableElements/store/relational/connection/DatasourceSpecification.ts
  packages/legend-graph/src/models/protocols/pure/v1/model/packageableElements/store/relational/connection/V1_DatasourceSpecification.ts
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/from/V1_ConnectionTransformer.ts
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureGraph/to/helpers/V1_RelationalConnectionBuilderHelper.ts
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureProtocol/serializationHelpers/V1_ConnectionSerializationHelper.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/relational-connection.pure
  packages/legend-studio/src/components/editor/edit-panel/connection-editor/RelationalDatabaseConnectionEditor.tsx
Labels: cla-present

#640 Add extension support for external language Morphir
  .changeset/bright-papayas-speak.md
  .changeset/four-pots-beam.md
  .changeset/nine-shrimps-sin.md
  packages/legend-extension-external-language-morphir/.npmignore
  packages/legend-extension-external-language-morphir/README.md
  packages/legend-extension-external-language-morphir/_package.config.js
  packages/legend-extension-external-language-morphir/jest.config.js
  packages/legend-extension-external-language-morphir/package.json
  packages/legend-extension-external-language-morphir/src/components/ELMorphir_LegendStudioPlugin.tsx
  packages/legend-extension-external-language-morphir/src/index.ts
  packages/legend-extension-external-language-morphir/tsconfig.build.json
  packages/legend-extension-external-language-morphir/tsconfig.json
  packages/legend-extension-external-language-morphir/tsconfig.package.json
  packages/legend-graph/src/models/protocols/pure/v1/engine/V1_Engine.ts
  packages/legend-graph/src/models/protocols/pure/v1/engine/generation/V1_FileGenerationInput.ts
  packages/legend-graph/src/models/protocols/pure/v1/model/context/V1_PureModelContextText.ts
  packages/legend-graph/src/models/protocols/pure/v1/transformation/pureProtocol/V1_PureProtocolSerialization.ts
  packages/legend-studio-app/package.json
  packages/legend-studio-app/src/index.tsx
  packages/legend-studio-app/tsconfig.json
  packages/legend-studio/src/components/editor/edit-panel/element-generation-editor/FileGenerationEditor.tsx
  packages/legend-studio/src/index.ts
  packages/legend-studio/src/stores/LegendStudioPlugin.ts
  packages/legend-studio/src/stores/editor-state/GraphGenerationState.ts
  packages/legend-studio/style/components/editor/_file-generation-editor.scss
  tsconfig.json
  yarn.lock
Labels: cla-present

#716 Use Join owner as the database owner when dragging join into RelationalMappingEditor
  .changeset/clean-moose-jump.md
  packages/legend-studio/src/components/editor/edit-panel/mapping-editor/relational/TableOrViewSourceTree.tsx
Labels: cla-present
