Repository finos/legend-studio, pull requests merged in 2022-09, with the labels that each got.

#1458 Refactor milestoning tests into test cases
  .changeset/many-jokes-grow.md
  packages/legend-application-query/src/components/__tests__/QueryBuilder_Milestoning.test.tsx
Labels: cla-present

#1462 fixes engine roundtrip test with indentation to pure file
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/relational-dataElement.pure
Labels: cla-present

#1463 minor bug fixes for query builder
  .changeset/heavy-buckets-attend.md
  .changeset/mean-cheetahs-hang.md
  .changeset/mean-knives-whisper.md
  package.json
  packages/babel-preset/package.json
  packages/eslint-plugin/package.json
  packages/legend-application-query-bootstrap/package.json
  packages/legend-application-query-deployment/package.json
  packages/legend-application-query/package.json
  packages/legend-application-query/src/stores/QueryBuilderPropertyEditorState.ts
  packages/legend-application-studio-bootstrap/package.json
  packages/legend-application-studio-deployment/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-taxonomy-bootstrap/package.json
  packages/legend-application-taxonomy-deployment/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-dev-utils/tsconfig.base.json
  packages/legend-extension-application-studio-management-toolkit/package.json
  packages/legend-extension-application-studio-query-builder/package.json
  packages/legend-extension-application-studio-query-builder/src/stores/QueryBuilder_EditorExtensionState.ts
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-mastery/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-external-format-json-schema/package.json
  packages/legend-extension-external-language-morphir/package.json
  packages/legend-extension-external-store-service/package.json
  packages/legend-extension-tracer-zipkin/package.json
  packages/legend-graph/package.json
  packages/legend-graph/src/graphManager/action/EngineError.ts
  packages/legend-manual-tests/package.json
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-storage/package.json
  scripts/typedoc-theme/package.json
  yarn.lock
Labels: cla-present

#1464 add use store model as option for full interactive
  .changeset/fuzzy-boats-fix.md
  .changeset/testing-mine-yours.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceRegistrationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/ServiceRegistrationTest.test.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceRegistrationState.ts
  packages/legend-graph/src/graphManager/AbstractPureGraphManager.ts
  packages/legend-graph/src/graphManager/action/service/ServiceExecutionMode.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/V1_Engine.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/V1_EngineServerClient.ts
Labels: cla-present

#1465 properly notify user when we can't open embedded query builder
  .changeset/friendly-cobras-bow.md
  packages/legend-application-studio/src/components/editor/StatusBar.tsx
  packages/legend-application-studio/src/components/shared/StudioLambdaEditor.tsx
  packages/legend-application-studio/src/index.ts
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-extension-application-studio-query-builder/src/components/__tests__/QueryBuilder_StudioPlugin.test.tsx
  packages/legend-extension-application-studio-query-builder/src/stores/QueryBuilder_EditorExtensionState.ts
Labels: cla-present

#1475 fix rendering of model importer extensions when switching between them
  .changeset/dirty-trainers-cover.md
  packages/legend-application-studio/src/stores/editor-state/ModelImporterState.ts
Labels: cla-present

#1434 feat: add mapper post processor editor
  .changeset/fowl-poultry-skedaddle.md
  .changeset/purple-donkeys-share.md
  packages/legend-application-studio/src/components/editor/edit-panel/UnsupportedElementEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/RelationalDatabaseConnectionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/post-processor-editor/MapperPostProcessorEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/InstanceSetImplementationEditor.tsx
  packages/legend-application-studio/src/index.ts
  packages/legend-application-studio/src/stores/StoreRelational_LegendStudioApplicationPlugin_Extension.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/connection/ConnectionEditorState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/connection/PostProcessorEditorState.ts
  packages/legend-application-studio/src/stores/graphModifier/StoreRelational_GraphModifierHelper.ts
  packages/legend-art/src/components/panel/Panel.tsx
  packages/legend-art/src/components/panel/PanelListSelectorItem.tsx
  packages/legend-art/src/index.ts
  packages/legend-art/style/base/_panel.scss
  packages/legend-graph/src/StoreRelational_Exports.ts
  packages/legend-graph/src/graph/Core_HashUtils.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/relational/connection/postprocessor/Mapper.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/relational/connection/postprocessor/PostProcessor.ts
  packages/legend-graph/src/graphManager/action/changeDetection/StoreRelational_ObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_PostProcessorTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_PostProcessorBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_PostProcessorSerializationHelper.ts
  packages/legend-graph/src/index.ts
Labels: cla-present

#1436 Allow loading query from inside of query builder
  .changeset/giant-coats-lay.md
  .changeset/proud-boxes-joke.md
  packages/legend-application-query-bootstrap/style/index.scss
  packages/legend-application-query/src/components/QueryEditor.tsx
  packages/legend-application-query/src/stores/QueryEditorStore.ts
  packages/legend-application-query/style/_query-editor.scss
Labels: cla-present

#1481 adds text example of mapper post processor
  .changeset/late-coats-tickle.md
  .changeset/silent-spies-shout.md
  .changeset/wise-feet-play.md
  packages/legend-application-studio/src/components/editor/edit-panel/GrammarTextEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/post-processor-editor/MapperPostProcessorEditor.tsx
  packages/legend-application-studio/src/stores/LegendStudioCodeSnippets.ts
  packages/legend-application-studio/src/stores/StoreRelational_LegendStudioApplicationPlugin_Extension.ts
  packages/legend-art/src/components/panel/Panel.tsx
  packages/legend-art/style/base/_panel.scss
  packages/legend-graph/src/graphManager/action/changeDetection/StoreRelational_ObserverHelper.ts
Labels: cla-present

#1483 fix: post processor snippet patch
  .changeset/chilled-radios-try.md
  packages/legend-application-studio/src/stores/LegendStudioCodeSnippets.ts
Labels: cla-present

#1487 fix: post processor state bug
  .changeset/gentle-bobcats-fry.md
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/connection/ConnectionEditorState.ts
Labels: cla-present, Type: Bug

#1489 Fix regression introduced for Parameter panel in #1457
  .changeset/serious-guests-tickle.md
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
Labels: cla-present

#1485 Add dependency info viewer
  .changeset/changes-more-stuff.md
  .changeset/dirty-beds-talk.md
  packages/legend-application-query-bootstrap/scripts/setup.js
  packages/legend-application-studio-bootstrap/scripts/setup.js
  packages/legend-application-studio/src/components/EditorComponentTestUtils.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/__tests__/ProjectConfigurationEditor.test.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/__tests__/TEST_DATA__ProjectDependencyInfo.ts
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectConfigurationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/ServiceRegistrationTest.test.tsx
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/LegendStudioAppEvent.ts
  packages/legend-application-studio/src/stores/__tests__/ProjectDependencyManager.test.ts
  packages/legend-application-studio/src/stores/editor-state/ProjectConfigurationEditorState.ts
  packages/legend-application-studio/style/components/editor/_project-configuration-editor.scss
  packages/legend-application-taxonomy-bootstrap/scripts/setup.js
  packages/legend-art/src/components/CJS__Icon.cts
  packages/legend-server-depot/src/DepotServerClient.ts
  packages/legend-server-depot/src/index.ts
  packages/legend-server-depot/src/models/ProjectDependencyInfo.ts
Labels: cla-present, Component: SDLC, Application: Studio

#1492 minor fixes to dependency info viewer
  .changeset/orange-sloths-bake.md
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectConfigurationEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/ProjectConfigurationEditorState.ts
Labels: cla-present

#1497 Query Loader -- minor query loader enhancements
  .changeset/silent-beds-drop.md
  packages/legend-application-query/src/components/QueryEditor.tsx
  packages/legend-application-query/src/stores/QueryEditorStore.ts
Labels: cla-present

#1498 Correct the `mine` filter of query editor's query loader
  .changeset/mean-flies-pay.md
  packages/legend-application-query/src/components/QueryEditor.tsx
Labels: cla-present

#1501 Fix a bug where query-builder crash when right-clicking the result panel if current query is not supported in form mode
  .changeset/thin-kings-sniff.md
  packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
Labels: cla-present

#1500 minor add label for post processor selector panel
  .changeset/fifty-badgers-complain.md
  .changeset/shaggy-shoes-knock.md
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/RelationalDatabaseConnectionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/post-processor-editor/MapperPostProcessorEditor.tsx
  packages/legend-art/src/components/Badge.tsx
  packages/legend-art/src/components/panel/PanelListSelectorItem.tsx
  packages/legend-art/src/index.ts
  packages/legend-art/style/base/_panel.scss
  packages/legend-art/style/components/_badge.scss
  packages/legend-art/style/index.scss
Labels: cla-present

#1513 fix hashStrings bug when generating test data
  .changeset/kind-hats-brush.md
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/execution/V1_ExecuteInput.ts
Labels: cla-present

#1510 doc: adding contributing doc guide
  CONTRIBUTING.md
  docs/ux/miscellaneous.md
  docs/ux/modality.md
  docs/ux/user-interface.md
  docs/workflow/docs.md
  docs/workflow/local-development-assemblage.md
Labels: cla-present

#1517 patch: codesmell
  .changeset/mighty-balloons-shake.md
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/post-processor-editor/MapperPostProcessorEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/testable/TestAssertionEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/ModelImporterState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceRegistrationState.ts
  packages/legend-extension-dsl-persistence/src/components/studio/DSL_Persistence_LegendStudioApplicationPlugin.tsx
  packages/legend-extension-dsl-service/src/stores/studio/ServiceQueryEditorStore.ts
Labels: cla-present

#1502 add panel section component
  .changeset/chicken-pigeon-duck.md
  .changeset/polite-queens-thank.md
  .changeset/purple-eyes-ring.md
  packages/legend-application-studio/src/components/editor/aux-panel/AuxiliaryPanel.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/FileGenerationViewer.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/FunctionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/GenerationSpecificationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/GrammarTextEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/RuntimeEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/UnsupportedElementEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/ConnectionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/DatabaseBuilder.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/RelationalDatabaseConnectionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/post-processor-editor/MapperPostProcessorEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/data-editor/EmbeddedDataEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/element-generation-editor/FileGenerationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/external-format-editor/SchemaSetElementEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/external-format-editor/SchemaSetModelGenerationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/EnumerationMappingEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/InstanceSetImplementationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/MappingEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/MappingExecutionBuilder.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/MappingTestEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/OperationSetImplementationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectConfigurationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/testable/TestAssertionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/AssociationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/ClassEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/EnumerationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/ProfileEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/PropertyEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/LocalChanges.tsx
  packages/legend-application-studio/src/components/editor/side-bar/ProjectOverview.tsx
  packages/legend-application-studio/src/components/editor/side-bar/WorkflowManager.tsx
  packages/legend-application-studio/src/components/editor/side-bar/WorkspaceReview.tsx
  packages/legend-application-studio/src/components/editor/side-bar/WorkspaceSyncConflictResolver.tsx
  packages/legend-application-studio/src/components/editor/side-bar/WorkspaceUpdateConflictResolver.tsx
  packages/legend-application-studio/src/components/editor/side-bar/WorkspaceUpdater.tsx
  packages/legend-application-studio/src/components/editor/side-bar/testable/GlobalTestRunner.tsx
  packages/legend-application-studio/src/components/workspace-review/WorkspaceReviewSideBar.tsx
  packages/legend-application-studio/src/index.ts
  packages/legend-application-taxonomy/src/components/TaxonomyExplorer.tsx
  packages/legend-application/src/components/shared/execution-plan-viewer/ExecutionPlanViewer.tsx
  packages/legend-art/src/components/panel/Panel.tsx
  packages/legend-art/style/base/_panel.scss
  packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderUnsupportedQueryEditor.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderFetchStructurePanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderPostFilterPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderProjectionPanel.tsx
  packages/legend-query-builder/src/components/filter/QueryBuilderFilterPanel.tsx
Labels: cla-present, Component: UX/Design

#1509 leverage depot to fetch dataSpace Analysis Result
  .changeset/silent-birds-rule.md
  .changeset/silent-chilly-birds.md
  .changeset/silent-cold-bird.md
  packages/legend-application-taxonomy/src/stores/StandaloneDataSpaceViewerStore.ts
  packages/legend-application-taxonomy/src/stores/TaxonomyNodeViewerState.ts
  packages/legend-extension-dsl-data-space/src/graphManager/action/analytics/DSL_DataSpace_DataSpaceAnalysisHelper.ts
  packages/legend-extension-dsl-data-space/src/graphManager/protocol/pure/DSL_DataSpace_PureGraphManagerExtension.ts
  packages/legend-extension-dsl-data-space/src/graphManager/protocol/pure/v1/V1_DSL_DataSpace_PureGraphManagerExtension.ts
  packages/legend-extension-dsl-data-space/src/index.ts
  packages/legend-extension-dsl-data-space/src/stores/query/DSL_DataSpace_DataSpaceQuerySetupState.ts
  packages/legend-graph/src/graph/helpers/ArtifactGenerationExtensionHelper.ts
  packages/legend-graph/src/graph/helpers/__tests__/ArtifactGenerationExtensionHelper.test.ts
  packages/legend-graph/src/graphManager/GraphManagerEvent.ts
  packages/legend-graph/src/index.ts
  packages/legend-server-depot/src/DepotServerClient.ts
Labels: cla-present
