Repository finos/legend-studio, pull requests merged in 2022-10, with the labels that each got.

#1522 minor improvements
  .changeset/config.json
  .changeset/little-weeks-arrive.md
  .eslintrc.cjs
  .github/codeql-config.yml
  .github/workflows/check-code.yml
  .github/workflows/check-security-and-quality.yml
  CONTRIBUTING.md
  docs/workflow/docs.md
  docs/workflow/writing-application-documentation.md
  fixtures/legend-mock-server/package.json
  package.json
  packages/eslint-plugin/src/configs/recommended.js
  packages/legend-application-query/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/RelationalDatabaseConnectionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/diff-editor/EntityChangeConflictEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/PropertyMappingsEditor.tsx
  packages/legend-application-studio/src/index.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/mapping/MappingElementState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/mapping/PureInstanceSetImplementationState.ts
  packages/legend-application-studio/src/stores/editor/NewElementState.ts
  packages/legend-application-studio/src/stores/project-viewer/ProjectViewerStore.ts
  packages/legend-application-studio/style/components/editor/_activity-bar.scss
  packages/legend-application-taxonomy/package.json
  packages/legend-application-taxonomy/src/stores/StandaloneDataSpaceViewerStore.ts
  packages/legend-application-taxonomy/src/stores/TaxonomyNodeViewerState.ts
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-data-space/src/graphManager/action/analytics/DSL_DataSpace_DataSpaceAnalysisHelper.ts
  packages/legend-extension-dsl-data-space/src/graphManager/protocol/pure/v1/V1_DSL_DataSpace_PureGraphManagerExtension.ts
  packages/legend-extension-dsl-data-space/src/stores/query/DSL_DataSpace_DataSpaceQuerySetupState.ts
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-mastery/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-service/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-external-format-json-schema/package.json
  packages/legend-extension-external-language-morphir/package.json
  packages/legend-extension-external-store-service/package.json
  packages/legend-extension-store-flat-data/package.json
  packages/legend-extension-store-relational/package.json
  packages/legend-extension-tracer-zipkin/package.json
  packages/legend-graph/package.json
  packages/legend-manual-tests/package.json
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/RoundtripGrammar.test.ts
  packages/legend-query-builder/package.json
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-shared/src/log/Logger.ts
  packages/legend-storage/package.json
  packages/stylelint-config/package.json
  scripts/github-bot/package.json
  sonar-project.properties
  yarn.lock
Labels: cla-present

#1525 minor fix to analyzeDataSpace
  .changeset/olive-pigs-beam.md
  packages/legend-extension-dsl-data-space/src/graphManager/action/analytics/DSL_DataSpace_DataSpaceAnalysisHelper.ts
  packages/legend-extension-dsl-data-space/src/graphManager/protocol/pure/DSL_DataSpace_PureGraphManagerExtension.ts
  packages/legend-extension-dsl-data-space/src/graphManager/protocol/pure/v1/V1_DSL_DataSpace_PureGraphManagerExtension.ts
  packages/legend-server-depot/src/DepotServerClient.ts
Labels: cla-present

#1528 fix: visual indicator for system elements
  .changeset/shiny-rockets-sing.md
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/EnumerationMappingEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/InstanceSetImplementationSourceSelectorModal.tsx
Labels: cla-present, Type: Bug, Application: Studio, Component: UX/Design, Extensions: DSL Mapping

#1534 standardize ports
  .changeset/six-yaks-kiss.md
  CONTRIBUTING.md
  README.md
  docs/workflow/code-contributor-guide.md
  fixtures/legend-docker-setup/end-to-end-setup/config/engine-config.json
  fixtures/legend-docker-setup/end-to-end-setup/end-to-end-setup-docker-compose.yml
  fixtures/legend-docker-setup/grammar-test-setup/config/engine-config.json
  fixtures/legend-docker-setup/grammar-test-setup/grammar-test-setup-docker-compose.yml
  packages/legend-application-query-bootstrap/scripts/setup.js
  packages/legend-application-query-deployment/Dockerfile
  packages/legend-application-query-deployment/README.md
  packages/legend-application-query-deployment/query.config.js
  packages/legend-application-query/CHANGELOG.md
  packages/legend-application-studio-bootstrap/scripts/setup.js
  packages/legend-application-studio-deployment/Dockerfile
  packages/legend-application-studio-deployment/README.md
  packages/legend-application-taxonomy-bootstrap/scripts/setup.js
  packages/legend-application-taxonomy-deployment/Dockerfile
  packages/legend-application-taxonomy-deployment/README.md
  packages/legend-application-taxonomy-deployment/taxonomy.config.js
  packages/legend-dev-utils/WebpackConfigUtils.js
  packages/legend-manual-tests/engine-config.json
Labels: cla-present

#1537 bump finos/legend-shared-server
  .changeset/quick-buckets-own.md
  docs/workflow/writing-application-documentation.md
  fixtures/legend-docker-setup/end-to-end-setup/config/engine-config.json
  fixtures/legend-docker-setup/end-to-end-setup/end-to-end-setup-docker-compose.yml
  fixtures/legend-docker-setup/grammar-test-setup/config/engine-config.json
  fixtures/legend-docker-setup/grammar-test-setup/grammar-test-setup-docker-compose.yml
  fixtures/legend-mock-server/src/index.ts
  packages/legend-application-query-bootstrap/scripts/setup.js
  packages/legend-application-query-deployment/Dockerfile
  packages/legend-application-studio-bootstrap/scripts/setup.js
  packages/legend-application-studio-deployment/Dockerfile
  packages/legend-application-taxonomy-bootstrap/scripts/setup.js
  packages/legend-application-taxonomy-deployment/Dockerfile
  packages/legend-manual-tests/engine-config.json
Labels: cla-present

#1544 assert query is supported during build lambda roundtrip tests
  .changeset/curvy-bears-fail.md
  packages/legend-query-builder/src/stores/__tests__/QueryBuilder_BuildLambdaRoundtrip.test.tsx
Labels: cla-present

#1504 Support duplicated property mapping for property type other than class
  .changeset/nervous-turtles-float.md
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/PropertyMappingsEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/mapping/MappingElementDecorator.ts
  packages/legend-application-studio/src/stores/graphModifier/DSL_Mapping_GraphModifierHelper.ts
  packages/legend-application-studio/style/components/editor/mapping-editor/_property-mapping-editor.scss
Labels: cla-present

#1543 minor improvements
  .changeset/smart-cows-tan.md
  packages/legend-application-studio/src/components/editor/edit-panel/FunctionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/AssociationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/ClassEditor.tsx
  packages/legend-extension-dsl-diagram/src/components/studio/DSL_Diagram_DiagramEditor.tsx
  packages/legend-extension-store-service-store/src/graphManager/protocol/pure/STO_ServiceStore_PureProtocolProcessorPlugin.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_MilestoneBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_ValueSpecificationBuilderHelper.ts
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
  packages/legend-query-builder/src/graphManager/protocol/pure/v1/V1_QueryBuilder_FunctionExpressionBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/projection/QueryBuilderProjectionValueSpecificationBuilder.ts
Labels: cla-present

#1538 Add parameter multiplicity validation for service registration
  .changeset/seven-flowers-sparkle.md
  .changeset/strong-lions-thank.md
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceRegistrationState.ts
  packages/legend-graph/src/graph/helpers/DomainHelper.ts
Labels: cla-present

#1546 fix: validation error for post processor mapper
  .changeset/rascally-ravens-ruminate.md
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/post-processor-editor/MapperPostProcessorEditor.tsx
Labels: cla-present

#1541 Add support for flatdata association mapping
  .changeset/young-dryers-attend.md
  packages/legend-graph/src/graph/Core_HashUtils.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/mapping/PropertyMapping.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/flatData/mapping/FlatDataAssociationImplementation.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/flatData/mapping/FlatDataAssociationPropertyMapping.ts
  packages/legend-graph/src/graphManager/__tests__/ImportResolutionRoundtrip.test.ts
  packages/legend-graph/src/graphManager/__tests__/roundtripTestData/TEST_DATA__FlatDataRoundtrip.ts
  packages/legend-graph/src/graphManager/action/changeDetection/DSL_Mapping_ObserverHelper.ts
  packages/legend-graph/src/graphManager/action/changeDetection/STO_FlatData_ObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/mapping/V1_PropertyMapping.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/flatData/mapping/V1_FlatDataAssociationMapping.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/flatData/mapping/V1_FlatDataAssociationPropertyMapping.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/V1_PropertyMappingBuilder.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_AssociationMappingHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_MappingSerializationHelper.ts
Labels: cla-present

#1507 Add basic tests for milestoning to accomodate testing via workflows
  .changeset/stale-hornets-film.md
  packages/legend-application-studio/src/components/__tests__/ClassQueryBuilder.test.tsx
  packages/legend-application-studio/src/components/__tests__/EmbeddedQueryBuilder.test.tsx
  packages/legend-application-studio/src/components/__tests__/TEST_DATA__ClassQueryBuilderModel.json
  packages/legend-query-builder/src/components/__tests__/QueryBuilder_Milestoning.test.tsx
  packages/legend-query-builder/src/stores/QueryBuilderState.ts
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder_Milestoning.ts
Labels: cla-present, Type: Regression, Component: Query Builder

#1547 Add extension mechanism for Testable
  .changeset/angry-buttons-relate.md
  .changeset/kind-months-provide.md
  packages/legend-extension-dsl-persistence/src/graphManager/DSL_Persistence_PureGraphManagerPlugin.ts
  packages/legend-extension-dsl-persistence/src/graphManager/protocol/pure/DSL_Persistence_PureProtocolProcessorPlugin.ts
  packages/legend-extension-dsl-persistence/src/graphManager/protocol/pure/v1/transformation/pureProtocol/V1_DSL_Persistence_ProtocolHelper.ts
  packages/legend-graph/src/graphManager/PureGraphManagerPlugin.ts
  packages/legend-graph/src/graphManager/Testable_PureGraphManagerPlugin_Extension.ts
  packages/legend-graph/src/graphManager/action/changeDetection/Testable_ObserverHelper.ts
  packages/legend-graph/src/graphManager/helpers/DSL_Data_GraphManagerHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/PureProtocolProcessorPlugin.ts
  packages/legend-graph/src/graphManager/protocol/pure/Testable_PureProtocolProcessorPlugin_Extension.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_TestTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_TestBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_TestResultBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_ServiceSerializationHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_TestSerializationHelper.ts
  packages/legend-graph/src/index.ts
Labels: cla-present, Priority: Refactor

#1554 Reset query loader state on closing
  .changeset/rude-owls-cheat.md
  packages/legend-application-query/src/components/QueryEditor.tsx
  packages/legend-application-query/src/stores/QueryEditorStore.ts
Labels: cla-present

#1553 fix a regression introduced in #1543
  .changeset/early-singers-serve.md
  .changeset/slimy-feet-fly.md
  .changeset/swift-lies-speak.md
  packages/legend-application-studio/src/stores/shared/modifier/DomainGraphModifierHelper.ts
  packages/legend-application-studio/src/stores/shared/modifier/RawValueSpecificationGraphModifierHelper.ts
  packages/legend-extension-store-service-store/src/graphManager/action/changeDetection/STO_ServiceStore_ObserverHelper.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/domain/Multiplicity.ts
  packages/legend-graph/src/graphManager/action/changeDetection/CoreObserverHelper.ts
  packages/legend-graph/src/graphManager/action/changeDetection/DSL_Mapping_ObserverHelper.ts
  packages/legend-graph/src/graphManager/action/changeDetection/DomainObserverHelper.ts
  packages/legend-graph/src/graphManager/action/changeDetection/RawValueSpecificationObserver.ts
  packages/legend-graph/src/graphManager/action/changeDetection/ValueSpecificationObserver.ts
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
  packages/legend-query-builder/src/stores/shared/LambdaParameterState.ts
  packages/legend-query-builder/src/stores/shared/ValueSpecificationModifierHelper.ts
Labels: cla-present

#1555 add generated milestone date properties
  .changeset/pretty-spies-deny.md
  .changeset/wow-expresso-machine.md
  packages/legend-extension-dsl-diagram/src/graphManager/__tests__/DSL_Diagram_BuildFailure.test.ts
  packages/legend-graph/src/graph/MetaModelConst.ts
  packages/legend-graph/src/graph/helpers/DomainHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/V1_ElementThirdPassBuilder.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_MilestoneBuilderHelper.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/class-generated-milestoning-properties.pure
  packages/legend-query-builder/src/stores/QueryBuilderMilestoningState.ts
  packages/legend-query-builder/src/stores/QueryBuilderPropertyEditorState.ts
Labels: cla-present

#1560 Make `PropertyExplicitReference` work with derived properties from association
  .changeset/stale-ducks-begin.md
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/domain/PropertyReference.ts
Labels: cla-present

#1567 fix a regression introduced by #1552
  .changeset/clever-beans-fly.md
  .changeset/twelve-pets-rest.md
  packages/legend-application-studio/src/components/editor/edit-panel/data-editor/RelationalCSVDataEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/element-generation-editor/ElementGenerationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/NewMappingElementModal.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/NewServiceModal.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestDataEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestableEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestsEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/CreateNewElementModal.tsx
  packages/legend-application-studio/src/components/editor/side-bar/WorkspaceReview.tsx
  packages/legend-application-studio/src/components/workspace-setup/CreateProjectModal.tsx
  packages/legend-application-studio/src/components/workspace-setup/CreateWorkspaceModal.tsx
  packages/legend-application-studio/src/components/workspace-setup/WorkspaceSetup.tsx
  packages/legend-application/src/components/ActionAlert.tsx
  packages/legend-extension-dsl-service/src/components/studio/ServiceQueryEditor.tsx
  packages/legend-extension-dsl-service/src/components/studio/ServiceQueryEditorReviewAction.tsx
  packages/legend-extension-dsl-service/src/components/studio/UpdateProjectServiceQuerySetup.tsx
  packages/legend-extension-dsl-service/src/components/studio/UpdateServiceQuerySetup.tsx
Labels: cla-present, Type: Regression

#1339 support function overloading
  .changeset/giant-clocks-stare.md
  .changeset/nine-baboons-act.md
  .changeset/twenty-glasses-enjoy.md
  packages/legend-application-studio/src/components/editor/edit-panel/FunctionEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
  packages/legend-application-studio/src/stores/shared/PackageTreeUtils.ts
  packages/legend-application-studio/src/stores/sidebar-state/LocalChangesState.ts
  packages/legend-graph/src/graph/BasicModel.ts
  packages/legend-graph/src/graph/helpers/DomainHelper.ts
  packages/legend-graph/src/graph/helpers/PureLanguageHelper.ts
  packages/legend-graph/src/graph/helpers/__tests__/PureLanguageHelper.test.ts
  packages/legend-graph/src/graphManager/__tests__/ImportResolutionRoundtrip.test.ts
  packages/legend-graph/src/graphManager/__tests__/roundtripTestData/TEST_DATA__DomainRoundtrip.ts
  packages/legend-graph/src/graphManager/action/changeDetection/DomainObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/helpers/V1_DomainHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/V1_ElementFirstPassBuilder.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/V1_ElementSecondPassBuilder.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/V1_PureProtocolSerialization.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/RoundtripGrammar.test.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/basic-function-overloading.pure
  packages/legend-query-builder/src/components/explorer/QueryBuilderFunctionsExplorerPanel.tsx
Labels: cla-present, Status: Waiting for Backend Change

#1586 change tds to TDS
  .changeset/odd-hairs-ring.md
  packages/legend-graph/src/graphManager/action/execution/ExecutionResult.ts
  packages/legend-graph/src/graphManager/action/execution/ExecutionResultHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/execution/V1_ExecutionHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/execution/V1_ExecutionResult.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/valueSpecification/V1_ValueSpecification.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/valueSpecification/raw/V1_TDSOlapAggregation_.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/valueSpecification/raw/V1_TDSOlapRank_.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_ValueSpecificationBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_ValueSpecificationPathResolver.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_ValueSpecificationSerializer.ts
  packages/legend-graph/src/index.ts
  packages/legend-query-builder/src/components/QueryBuilder.tsx
  packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderOlapGroupByPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderPostFilterPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderTDSComponentHelper.tsx
  packages/legend-query-builder/src/stores/QueryBuilderTypeaheadHelper.ts
  packages/legend-query-builder/src/stores/__tests__/QueryBuilderBuildLambdaRoundtrip.test.tsx
  packages/legend-query-builder/src/stores/explorer/QueryBuilderExplorerState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/QueryBuilderTDSColumnState_.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/QueryBuilderTDSHelper.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/QueryBuilderTDSState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/aggregation/QueryBuilderAggregationState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOlapGroupByOperatorLoader.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOlapGroupByState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOlapGroupByStateBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDSOlapOperator_.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDSOlapOperator_Average.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDSOlapOperator_Count.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDSOlapOperator_Max.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDSOlapOperator_Min.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDSOlapOperator_Sum.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDSOlapRankOperator_AverageRank_.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDSOlapRankOperator_DenseRank_.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDSOlapRankOperator_Rank_.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDSOlapRankOperator_RowNumber_.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/QueryBuilderPostFilterOperator.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/QueryBuilderPostFilterState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/QueryBuilderPostFilterStateBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/operators/QueryBuilderPostFilterOperatorHelper.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/operators/QueryBuilderPostFilterOperatorValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/operators/QueryBuilderPostFilterOperator_IsEmpty.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/projection/QueryBuilderProjectionColumnState.ts
Labels: cla-present

#1601 minor fix and bump dependencies
  .changeset/spicy-humans-sell.md
  package.json
  packages/babel-preset/package.json
  packages/legend-application-query-bootstrap/package.json
  packages/legend-application-query/package.json
  packages/legend-application-studio-bootstrap/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-studio/src/components/editor/aux-panel/DevTool.tsx
  packages/legend-application-taxonomy-bootstrap/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-mastery/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-service/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-store-flat-data/package.json
  packages/legend-extension-store-relational/package.json
  packages/legend-extension-store-service-store/package.json
  packages/legend-query-builder/package.json
  scripts/typedoc-theme/package.json
  yarn.lock
Labels: cla-present
