Repository finos/legend-studio, pull requests merged in 2022-11, with the labels that each got.

#1610 fix: remove display of dependency problems
  .changeset/pilfering-puffins-plunder.md
  .changeset/sweet-cobras-clean.md
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/RelationalDatabaseConnectionEditor.tsx
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-art/style/base/_panel.scss
Labels: cla-present

#1611 fix: select all properties from root class in explorer
  .changeset/eight-ways-brake.md
  packages/legend-query-builder/src/components/explorer/QueryBuilderExplorerPanel.tsx
Labels: cla-present, Type: Bug, Component: Query Builder

#1613 fix: test to select all properties from root class in explorer
  .changeset/soft-trains-wave.md
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
  packages/legend-query-builder/src/components/__tests__/QueryBuilderFetchStructure.test.tsx
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__ModelCoverageAnalysisResult.ts
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder_Model_SimpleSubtype.json
Labels: cla-present, Component: Query Builder, Component: Testing

#1591 OlapGroupBy Cleanups
  .changeset/plenty-jobs-kiss.md
  packages/legend-application-query-bootstrap/style/index.scss
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/valueSpecification/raw/classInstance/V1_TDSOlapAggregation.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/valueSpecification/raw/classInstance/V1_TDSOlapRank.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_ValueSpecificationPathResolver.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_ValueSpecificationSerializer.ts
  packages/legend-query-builder/src/components/QueryBuilder.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderOLAPGroupByPanel_.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderPostFilterPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderPostTDSPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderTDSComponentHelper.tsx
  packages/legend-query-builder/src/graphManager/QueryBuilderHashUtils.ts
  packages/legend-query-builder/src/graphManager/protocol/pure/QueryBuilder_PureProtocolProcessorPlugin.ts
  packages/legend-query-builder/src/graphManager/protocol/pure/v1/V1_QueryValueSpecificationBuilderHelper.ts
  packages/legend-query-builder/src/stores/QueryBuilderStateBuilder.ts
  packages/legend-query-builder/src/stores/__tests__/QueryBuilderBuildLambdaRoundtrip.test.tsx
  packages/legend-query-builder/src/stores/__tests__/QueryBuilderProcessingRoundtrip.test.ts
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder_OLAPGroupBy_.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/QueryBuilderTDSColumnState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/QueryBuilderTDSHelper.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/QueryBuilderTDSState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/aggregation/QueryBuilderAggregationState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOLAPGroupByOperatorLoader_.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOLAPGroupByStateBuilder_.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOLAPGroupByState_.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOLAPGroupByValueSpecificationBuilder_.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOlapGroupByOperatorLoader.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDS_OLAPOperator.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDS_OLAPOperator_Average.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDS_OLAPOperator_Count.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDS_OLAPOperator_Max.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDS_OLAPOperator_Min.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDS_OLAPOperator_Sum.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDS_OLAPRankOperator_AverageRank.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDS_OLAPRankOperator_DenseRank.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDS_OLAPRankOperator_Rank.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/operators/QueryBuilderTDS_OLAPRankOperator_RowNumber.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/QueryBuilderPostFilterState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/QueryBuilderPostFilterStateBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/operators/QueryBuilderPostFilterOperatorHelper.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/projection/QueryBuilderProjectionColumnState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/projection/QueryBuilderProjectionValueSpecificationBuilder.ts
  packages/legend-query-builder/style/_query-builder-olap.scss
Labels: cla-present

#1572 Leverage engine to execute queries with parameters
  .changeset/stale-trains-agree.md
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceExecutionState.ts
  packages/legend-graph/src/graphManager/AbstractPureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/execution/V1_ExecuteInput.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_ServiceTransformer.ts
  packages/legend-query-builder/src/components/__tests__/QueryBuilderExecution.test.tsx
  packages/legend-query-builder/src/components/__tests__/TEST_DATA_QueryBuilder_QueryExecution_Entities.json
  packages/legend-query-builder/src/components/__tests__/TEST_DATA_QueryBuilder_Query_Execution.ts
  packages/legend-query-builder/src/stores/QueryBuilderResultState.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/shared/LambdaParameterState.ts
Labels: cla-present, Status: Waiting for Backend Change

#1618 block more native platform hotkeys in Windows
  .changeset/lemon-crabs-joke.md
  .changeset/nice-singers-battle.md
  package.json
  packages/babel-preset/package.json
  packages/legend-application/src/components/LegendApplicationComponentFrameworkProvider.tsx
  packages/legend-query-builder/package.json
  yarn.lock
Labels: cla-present

#1619 block more native platform hotkeys in Windows
  .changeset/fuzzy-comics-knock.md
  packages/legend-application/src/components/LegendApplicationComponentFrameworkProvider.tsx
Labels: cla-present

#1626 minor improvements
  .changeset/lemon-snails-brush.md
  packages/legend-application-query/src/index.ts
  packages/legend-application-query/src/stores/CloneServiceQuerySetupStore.ts
  packages/legend-application-query/src/stores/CreateMappingQuerySetupStore.ts
  packages/legend-application-query/src/stores/LegendQueryAppEvent.ts
  packages/legend-application-query/src/stores/LegendQueryEventService.ts
  packages/legend-application-query/src/stores/LegendQueryTelemetry.ts
  packages/legend-application-query/src/stores/QueryEditorStore.ts
  packages/legend-application-query/src/stores/QuerySetupStore.ts
  packages/legend-application-studio/src/components/editor/Editor.tsx
  packages/legend-application/src/components/LegendApplicationComponentFrameworkProvider.tsx
  packages/legend-application/src/stores/WebApplicationNavigator.ts
  packages/legend-query-builder/src/components/QueryBuilderNavigationBlocker.tsx
Labels: cla-present

#1623 Update sequent lambda names once the filter root lambda parameter name is changed
  .changeset/tiny-readers-taste.md
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/projection/QueryBuilderProjectionValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/filter/operators/QueryBuilderFilterOperatorValueSpecificationBuilder.ts
Labels: cla-present

#1628 Improve editing of multiplicity for parameters in query builder
  .changeset/khaki-parents-pump.md
  .changeset/lazy-garlics-refuse.md
  packages/legend-graph/src/graph/helpers/DomainHelper.ts
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
Labels: cla-present

#1659 fix building of data element when referenced in dependency model
  .changeset/fuzzy-worms-sit.md
  packages/legend-graph/src/graph/DependencyManager.ts
Labels: cla-present

#1662 add field descriptions to model connector
  .changeset/modern-impalas-join.md
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/ConnectionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/NewServiceModal.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionQueryEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/CreateNewElementModal.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/connection/ConnectionEditorState.ts
Labels: cla-present, Studio Core Team, Application: Studio

#1667 make scrollbar lighter in dark mode selector
  .changeset/silent-bobcats-poke.md
  packages/legend-art/src/components/CustomSelectorInput.tsx
  packages/legend-art/style/base/_normalize.scss
Labels: cla-present, Studio Core Team, Application: Studio, Component: UX/Design

#1670 ensure to decode query parameters
  .changeset/metal-jeans-doubt.md
  packages/legend-application-query/src/components/QueryEditor.tsx
  packages/legend-application-query/src/components/QuerySetup.tsx
  packages/legend-application-query/src/stores/LegendQueryRouter.ts
  packages/legend-extension-dsl-data-space/src/components/query/DataSpaceQueryCreator.tsx
  packages/legend-extension-dsl-data-space/src/stores/query/DSL_DataSpace_LegendQueryRouter.ts
  packages/legend-shared/src/network/NetworkUtils.ts
Labels: cla-present

#1668 fix two regressions introduced by #1572 and #1628
  .changeset/modern-gifts-nail.md
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceExecutionState.ts
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
  packages/legend-query-builder/src/stores/QueryBuilderResultState.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/shared/LambdaParameterState.ts
Labels: cla-present

#1663 Add an icon to open service test doc
  .changeset/mighty-fireants-report.md
  .changeset/thirty-readers-provide.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceEditor.tsx
  packages/legend-application-studio/style/components/editor/_service-editor.scss
  packages/legend-application/src/stores/LegendApplicationDocumentation.ts
Labels: cla-present

#1678 fix: group workspace toogle creation
  .changeset/witty-games-wonder.md
  packages/legend-art/src/components/panel/Panel.tsx
Labels: cla-present, Type: Bug, Studio Core Team, Application: Studio

#1676 Add project configuration panel shortcut to project explorer action panel
  .changeset/plenty-terms-bow.md
  packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
  packages/legend-application-studio/style/components/editor/side-bar/_explorer.scss
Labels: cla-present

#1559 Refactor milestoning code
  .changeset/weak-lies-relax.md
  packages/legend-graph/src/graph/metamodel/pure/valueSpecification/INTERNAL__PropagatedValue.ts
  packages/legend-query-builder/src/components/QueryBuilderPropertyExpressionEditor.tsx
  packages/legend-query-builder/src/components/QueryBuilderSideBar.tsx
  packages/legend-query-builder/src/stores/QueryBuilderPropertyEditorState.ts
  packages/legend-query-builder/src/stores/QueryBuilderState.ts
  packages/legend-query-builder/src/stores/QueryBuilderStateBuilder.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationHelper.ts
  packages/legend-query-builder/src/stores/milestoning/QueryBuilderBitemporalMilestoningImplementation.ts
  packages/legend-query-builder/src/stores/milestoning/QueryBuilderBusinessTemporalMilestoningImplementation.ts
  packages/legend-query-builder/src/stores/milestoning/QueryBuilderMilestoningHelper.ts
  packages/legend-query-builder/src/stores/milestoning/QueryBuilderMilestoningImplementation.ts
  packages/legend-query-builder/src/stores/milestoning/QueryBuilderMilestoningState.ts
  packages/legend-query-builder/src/stores/milestoning/QueryBuilderProcessingTemporalMilestoningImplementation.ts
Labels: cla-present

#1682 fix: keeping query states when switching execution contexts
  .changeset/swift-rockets-draw.md
  packages/legend-query-builder/src/stores/QueryBuilderState.ts
  packages/legend-query-builder/src/stores/workflows/ServiceQueryBuilderState.ts
Labels: cla-present, Type: Bug, Component: Query Builder

#1680 Fix incorrectly creating parameters for milestone date values when not required
  .changeset/sixty-ties-search.md
  packages/legend-query-builder/src/stores/QueryBuilderStateBuilder.ts
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder_Milestoning.ts
  packages/legend-query-builder/src/stores/milestoning/QueryBuilderMilestoningState.ts
Labels: cla-present

#1658 fix: toogle text mode shortcut in viewer mode
  .changeset/finicky-falcons-feign.md
  packages/legend-application-studio/src/stores/EditorStore.ts
Labels: cla-present, Type: Bug, Studio Core Team, Application: Studio

#1684 Fix a bug with diagram property view referencing association
  .changeset/brave-llamas-try.md
  .changeset/slow-rabbits-beg.md
  packages/legend-extension-dsl-diagram/src/graphManager/__tests__/DSL_Diagram_Roundtrip.test.ts
  packages/legend-extension-dsl-diagram/src/graphManager/__tests__/TEST_DATA__DSL_Diagram_Roundtrip.ts
  packages/legend-graph/src/graph/PureModel.ts
  packages/legend-graph/src/graph/helpers/DomainHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/V1_GraphBuilderContext.ts
Labels: cla-present

#1627 Add support for constants in query builder
  .changeset/chatty-geese-help.md
  .changeset/chatty-geese-second.md
  packages/legend-application-query-bootstrap/style/index.scss
  packages/legend-application-studio/src/components/editor/edit-panel/external-format-editor/DSL_ExternalFormat_SchemaSetModelGenerationEditor.tsx
  packages/legend-graph/src/graph/metamodel/pure/valueSpecification/LambdaFunction.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_ValueSpecificationBuilderHelper.ts
  packages/legend-query-builder/src/components/QueryBuilder.tsx
  packages/legend-query-builder/src/components/QueryBuilderConstantExpressionPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderPropertyExpressionEditor.tsx
  packages/legend-query-builder/src/components/explorer/QueryBuilderMilestoningEditor.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderOLAPGroupByPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderPostFilterPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderPostTDSPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderTDSPanel.tsx
  packages/legend-query-builder/src/components/filter/QueryBuilderFilterPanel.tsx
  packages/legend-query-builder/src/components/shared/BasicValueSpecificationEditor.tsx
  packages/legend-query-builder/src/components/shared/QueryBuilderVariableSelector.tsx
  packages/legend-query-builder/src/components/watermark/QueryBuilderWatermark.tsx
  packages/legend-query-builder/src/graphManager/QueryBuilderHashUtils.ts
  packages/legend-query-builder/src/stores/QueryBuilderConfig.ts
  packages/legend-query-builder/src/stores/QueryBuilderConstantsState.ts
  packages/legend-query-builder/src/stores/QueryBuilderParametersState.ts
  packages/legend-query-builder/src/stores/QueryBuilderState.ts
  packages/legend-query-builder/src/stores/QueryBuilderStateBuilder.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationHelper.ts
  packages/legend-query-builder/src/stores/__tests__/QueryBuilderBuildLambdaRoundtrip.test.tsx
  packages/legend-query-builder/src/stores/__tests__/QueryBuilderProcessingRoundtrip.test.ts
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder_ConstantExpression.ts
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder_OLAPGroupBy.ts
  packages/legend-query-builder/src/stores/fetch-structure/graph-fetch/QueryBuilderGraphFetchTreeStateBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/QueryBuilderTDSState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/aggregation/QueryBuilderAggregationStateBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOLAPGroupByOperatorLoader.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOLAPGroupByState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOLAPGroupByStateBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOLAPGroupByValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/operators/QueryBuilderPostFilterOperatorHelper.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/projection/QueryBuilderProjectionStateBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/projection/QueryBuilderProjectionValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/filter/QueryBuilderFilterValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/shared/ValueSpecificationEditorHelper.ts
  packages/legend-query-builder/src/stores/watermark/QueryBuilderWatermarkStateBuilder.ts
  packages/legend-query-builder/src/stores/watermark/QueryBuilderWatermarkValueSpecificationBuilder.ts
  packages/legend-query-builder/style/_query-builder-explorer.scss
  packages/legend-query-builder/style/_query-builder.scss
  packages/legend-query-builder/style/shared/_value-spec-editor.scss
Labels: cla-present

#1689 minor cleanups
  .changeset/fifty-donkeys-travel.md
  .changeset/rich-snakes-develop.md
  .github/ISSUE_TEMPLATE/Planning.yml
  package.json
  packages/eslint-plugin/package.json
  packages/legend-application-query/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-studio/src/components/Core_LegendStudioApplicationPlugin.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectConfigurationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/ServiceRegistrationTest.test.tsx
  packages/legend-application-studio/src/stores/LegendStudioBaseStore.ts
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-art/src/components/panel/PanelDropZone.tsx
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-mastery/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-service/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-dsl-text/src/stores/studio/DSL_Text_LegendStudioApplicationNavigationContext.ts
  packages/legend-extension-store-flat-data/package.json
  packages/legend-extension-store-relational/package.json
  packages/legend-extension-store-service-store/package.json
  packages/legend-graph/package.json
  packages/legend-query-builder/package.json
  packages/legend-query-builder/src/components/__tests__/QueryBuilderFetchStructure.test.tsx
  packages/legend-query-builder/src/components/__tests__/QueryBuilderPropertySearch.test.tsx
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  scripts/typedoc-theme/package.json
  yarn.lock
Labels: cla-present

#1691 disable deleting used variable
  .changeset/shaggy-gorillas-hope.md
  .changeset/tame-kiwis-think.md
  packages/legend-application-studio/src/components/editor/StatusBar.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectConfigurationEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/ProjectConfigurationEditorState.ts
  packages/legend-application-studio/style/components/editor/_project-configuration-editor.scss
  packages/legend-query-builder/src/components/QueryBuilderConstantExpressionPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
  packages/legend-query-builder/src/components/shared/QueryBuilderVariableSelector.tsx
  packages/legend-query-builder/src/stores/QueryBuilderState.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationHelper.ts
  packages/legend-query-builder/src/stores/fetch-structure/QueryBuilderFetchStructureImplementationState.ts
  packages/legend-query-builder/src/stores/fetch-structure/graph-fetch/QueryBuilderGraphFetchTreeState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/QueryBuilderTDSState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/QueryBuilderPostFilterState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/projection/QueryBuilderProjectionColumnState.ts
  packages/legend-query-builder/src/stores/filter/QueryBuilderFilterState.ts
  packages/legend-query-builder/src/stores/milestoning/QueryBuilderMilestoningState.ts
  packages/legend-query-builder/src/stores/watermark/QueryBuilderWatermarkState.ts
Labels: cla-present

#1694 minor fixes
  .changeset/shaggy-colts-rest.md
  packages/legend-application/src/stores/LegendApplicationDocumentation.ts
  packages/legend-graph/src/graph/MetaModelUtils.ts
  packages/legend-query-builder/src/components/QueryBuilderConstantExpressionPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
  packages/legend-query-builder/src/components/shared/CustomDatePicker.tsx
  packages/legend-query-builder/style/_query-builder-explorer.scss
Labels: cla-present

#1607 Mastery ID refactoring to use identifiers.
  .changeset/sixty-comics-return.md
  packages/legend-extension-dsl-mastery/src/components/studio/DSL_Mastery_CodeSnippets.ts
Labels: cla-present, Status: Waiting for Backend Change

#1696 minor fixes
  .changeset/plenty-suns-jam.md
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectConfigurationEditor.tsx
Labels: cla-present

#1697 Remove Service's parameter icon and added the prompt below the header
  .changeset/swift-birds-sparkle.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceEditor.tsx
  packages/legend-application-studio/style/components/editor/_service-editor.scss
Labels: cla-present

#1679 Support contextual documentation for service test and add a doc icon for connection test data
  .changeset/swift-hounds-knock.md
  packages/legend-application-studio/src/components/editor/edit-panel/data-editor/DataElementEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestDataEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestableEditor.tsx
  packages/legend-application-studio/src/stores/LegendStudioApplicationNavigationContext.ts
  packages/legend-application-studio/src/stores/LegendStudioDocumentation.ts
  packages/legend-application-studio/style/components/editor/_data-editor.scss
  packages/legend-application-studio/style/components/editor/_external-format-editor.scss
  packages/legend-application/src/stores/LegendApplicationDocumentation.ts
Labels: cla-present

#1700 fix:turn on seconds in the datetime picker
  .changeset/quick-colts-impress.md
  packages/legend-query-builder/src/components/shared/CustomDatePicker.tsx
Labels: cla-present

#1705 fix:Fix a bug where re-editing `filter`and `post filter` input is not possible
  .changeset/shy-pears-beg.md
  packages/legend-query-builder/src/components/shared/BasicValueSpecificationEditor.tsx
Labels: cla-present

#1706 fix problems with keyboard
  .changeset/fifty-donkeys-travel.md
  .changeset/gorgeous-lobsters-accept.md
  .changeset/hot-waves-grab.md
  .changeset/rich-snakes-develop.md
  .changeset/twenty-poems-fry.md
  .github/workflows/check-code.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  fixtures/legend-mock-server/package.json
  package.json
  packages/babel-preset/package.json
  packages/legend-application-query-bootstrap/package.json
  packages/legend-application-query-deployment/package.json
  packages/legend-application-query/package.json
  packages/legend-application-studio-bootstrap/package.json
  packages/legend-application-studio-deployment/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-taxonomy-bootstrap/package.json
  packages/legend-application-taxonomy-deployment/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-application/src/application/LegendApplication.tsx
  packages/legend-application/src/components/LegendApplicationComponentFrameworkProvider.tsx
  packages/legend-application/src/stores/KeyboardShortcutsService.ts
  packages/legend-application/src/stores/PureLanguageSupport.ts
  packages/legend-art/package.json
  packages/legend-art/style/base/_modal.scss
  packages/legend-dev-utils/WebpackConfigUtils.js
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-diagram/src/DiagramRenderer.ts
  packages/legend-extension-dsl-mastery/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-service/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-format-json-schema/package.json
  packages/legend-extension-format-morphir/package.json
  packages/legend-extension-store-flat-data/package.json
  packages/legend-extension-store-relational/package.json
  packages/legend-extension-store-service-store/package.json
  packages/legend-extension-tracer-zipkin/package.json
  packages/legend-graph/package.json
  packages/legend-manual-tests/package.json
  packages/legend-query-builder/package.json
  packages/legend-query-builder/src/components/shared/CustomDatePicker.tsx
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-shared/src/index.ts
  packages/legend-shared/src/keyboard/KeyBinding.ts
  packages/legend-storage/package.json
  scripts/typedoc-theme/package.json
  yarn.lock
Labels: cla-present, Type: Bug

#1708 Support DnD from `fetch structure` to `filter` panel to create a new logical group
  .changeset/cool-wombats-relate.md
  packages/legend-query-builder/src/components/filter/QueryBuilderFilterPanel.tsx
Labels: cla-present

#1714 fix a regression introduced by #1705
  .changeset/big-worms-share.md
  packages/legend-art/src/components/CustomSelectorInput.tsx
Labels: cla-present

#1716 bump dependencies
  .changeset/flat-mugs-study.md
  .changeset/ten-berries-wait.md
  .github/workflows/check-code.yml
  fixtures/legend-mock-server/package.json
  package.json
  packages/babel-preset/package.json
  packages/eslint-plugin/package.json
  packages/legend-application-query-bootstrap/package.json
  packages/legend-application-query-deployment/package.json
  packages/legend-application-query/package.json
  packages/legend-application-studio-bootstrap/package.json
  packages/legend-application-studio-deployment/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-taxonomy-bootstrap/package.json
  packages/legend-application-taxonomy-deployment/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-art/src/components/CJS__ReactSelect.cts
  packages/legend-art/src/components/CustomSelectorInput.tsx
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-mastery/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-service/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-format-json-schema/package.json
  packages/legend-extension-format-morphir/package.json
  packages/legend-extension-store-flat-data/package.json
  packages/legend-extension-store-relational/package.json
  packages/legend-extension-store-service-store/package.json
  packages/legend-extension-tracer-zipkin/package.json
  packages/legend-graph/package.json
  packages/legend-manual-tests/package.json
  packages/legend-query-builder/package.json
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-storage/package.json
  packages/stylelint-config/package.json
  scripts/typedoc-theme/package.json
  yarn.lock
Labels: cla-present

#1719 Support env keys selection for each test in multi-exec services
  .changeset/green-cougars-relate.md
  .changeset/nasty-donuts-sing.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestsEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestEditorState.ts
  packages/legend-application-studio/src/stores/shared/modifier/DSL_Service_GraphModifierHelper.ts
  packages/legend-application-studio/style/components/editor/_service-editor.scss
  packages/legend-art/style/components/_selector-input.scss
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/service/ServiceTest.ts
  packages/legend-graph/src/graphManager/__tests__/roundtripTestData/TEST_DATA__ServiceRoundtrip.ts
  packages/legend-graph/src/graphManager/action/changeDetection/DSL_Service_ObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/service/V1_ServiceTest.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_ServiceTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_ServiceBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_ServiceSerializationHelper.ts
Labels: cla-present

#1717 Fix bug with not closing editorState after deleting the element in form mode
  .changeset/fair-carrots-try.md
  packages/legend-application-studio/src/stores/EditorStore.ts
Labels: cla-present, Component: UX/Design

#1722 add support for `OUTER` join alias
  .changeset/modern-mirrors-try.md
  .changeset/quiet-chicken-eat.md
  .changeset/wild-buttons-sell.md
  package.json
  packages/eslint-plugin/package.json
  packages/legend-application-query/src/components/EditExistingQuerySetup.tsx
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-graph/src/graph/helpers/STO_Relational_Helper.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/relational/model/RelationalOperationElement.ts
  packages/legend-manual-tests/package.json
  yarn.lock
Labels: cla-present

#1723 Revert "Support env keys selection for each test in multi-exec services (#1719)"
  .changeset/strong-zoos-confess.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestsEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestEditorState.ts
  packages/legend-application-studio/src/stores/shared/modifier/DSL_Service_GraphModifierHelper.ts
  packages/legend-application-studio/style/components/editor/_service-editor.scss
  packages/legend-art/style/components/_selector-input.scss
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/service/ServiceTest.ts
  packages/legend-graph/src/graphManager/__tests__/roundtripTestData/TEST_DATA__ServiceRoundtrip.ts
  packages/legend-graph/src/graphManager/action/changeDetection/DSL_Service_ObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/service/V1_ServiceTest.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_ServiceTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_ServiceBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_ServiceSerializationHelper.ts
Labels: cla-present

#1727 Enable virtual assistant for all applications
  .changeset/six-geckos-shake.md
  .changeset/spicy-vans-add.md
  packages/legend-application-query-bootstrap/scripts/setup.js
  packages/legend-application-query/src/components/QuerySetup.tsx
  packages/legend-application-query/style/_query-setup.scss
  packages/legend-application-studio-bootstrap/scripts/setup.js
  packages/legend-application-studio/src/components/LegendStudioApplication.tsx
  packages/legend-application-taxonomy-bootstrap/scripts/setup.js
  packages/legend-application-taxonomy/src/components/TaxonomyExplorer.tsx
  packages/legend-application/src/components/LegendApplicationComponentFrameworkProvider.tsx
  packages/legend-application/src/index.ts
  packages/legend-query-builder/src/components/QueryBuilder.tsx
Labels: cla-present

#1732 fix conflict messages in dependency fetch
  .changeset/flat-crews-reply.md
  packages/legend-application-studio/src/stores/EditorGraphState.ts
Labels: cla-present

#1733 bump dependencies
  .changeset/green-spoons-grab.md
  package.json
  packages/babel-preset/package.json
  packages/eslint-plugin/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/fileGeneration/ConfigurationProperty.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/fileGeneration/V1_ConfigurationProperty.ts
  packages/legend-shared/package.json
  packages/legend-shared/src/application/HashUtils.ts
  packages/stylelint-config/package.json
  scripts/release/preparePublishContent.js
  scripts/website/prepareSiteContent.js
  scripts/workflow/setupLocalDevAssemblage.js
  yarn.lock
Labels: cla-present

#1728 Revert "Revert "Support env keys selection for each test in multi-exec services (#1719)" (#1723)"
  .changeset/fresh-mails-flow.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestsEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestEditorState.ts
  packages/legend-application-studio/src/stores/shared/modifier/DSL_Service_GraphModifierHelper.ts
  packages/legend-application-studio/style/components/editor/_service-editor.scss
  packages/legend-art/style/components/_selector-input.scss
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/service/ServiceTest.ts
  packages/legend-graph/src/graphManager/__tests__/roundtripTestData/TEST_DATA__ServiceRoundtrip.ts
  packages/legend-graph/src/graphManager/action/changeDetection/DSL_Service_ObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/service/V1_ServiceTest.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_ServiceTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_ServiceBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_ServiceSerializationHelper.ts
Labels: cla-present, Status: Waiting for Backend Change
