Repository finos/legend-studio, pull requests merged in 2022-08, with the labels that each got.

#1351 fix regression: do not highlight property icon when it is unmapped
  .changeset/tiny-beans-attend.md
  packages/legend-application-query/style/_query-builder-explorer.scss
Labels: cla-present, Type: Regression

#1350 allow DnD from projection to filter
  .changeset/cyan-otters-exercise.md
  packages/legend-application-query/src/components/QueryBuilderFilterPanel.tsx
  packages/legend-application-query/src/stores/QueryBuilderFilterState.ts
Labels: cla-present

#1361 Support persistence trigger extensions
  .changeset/long-gifts-vanish.md
  packages/legend-extension-dsl-persistence/src/graph/metamodel/pure/model/packageableElements/persistence/DSLPersistence_Sink.ts
  packages/legend-extension-dsl-persistence/src/graphManager/protocol/pure/DSLPersistence_PureProtocolProcessorPlugin.ts
  packages/legend-extension-dsl-persistence/src/graphManager/protocol/pure/DSLPersistence_PureProtocolProcessorPlugin_Extension.ts
  packages/legend-extension-dsl-persistence/src/graphManager/protocol/pure/v1/model/packageableElements/persistence/V1_DSLPersistence_Sink.ts
  packages/legend-extension-dsl-persistence/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_PersistenceTransformer.ts
  packages/legend-extension-dsl-persistence/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/V1_PersistenceBuilder.ts
  packages/legend-extension-dsl-persistence/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/V1_PersistenceContextBuilder.ts
  packages/legend-extension-dsl-persistence/src/graphManager/protocol/pure/v1/transformation/pureProtocol/V1_DSLPersistence_ProtocolHelper.ts
  packages/legend-extension-dsl-persistence/src/index.ts
Labels: cla-present, Status: Waiting for Backend Change

#1180 Fix recursive viewing of parent class in explorer tree of query builder
  .changeset/thirty-kids-begin.md
  packages/legend-application-query/src/components/QueryBuilderExplorerPanel.tsx
  packages/legend-application-query/src/components/QueryBuilderPropertySearchPanel.tsx
  packages/legend-application-query/src/stores/QueryBuilderExplorerState.ts
  packages/legend-application-query/src/stores/QueryBuilderPropertySearchPanelState.ts
Labels: cla-present

#1358 support query execution cancellation
  .changeset/modern-ducks-confess.md
  packages/legend-application-query/src/components/QueryBuilderResultPanel.tsx
  packages/legend-application-query/src/stores/QueryBuilderResultState.ts
  packages/legend-application-query/style/_query-builder.scss
Labels: cla-present

#1378 fix generated expected result for multi execution
  .changeset/hot-news-juggle.md
  .changeset/my-news-fake.md
  packages/legend-application/src/components/shared/CustomDatePicker.tsx
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
Labels: cla-present

#1377 allow query execution cancellation for mapping/service editor
  .changeset/happy-scissors-grab.md
  .changeset/honest-waves-matter.md
  packages/legend-application-query/src/components/QueryBuilderResultPanel.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/MappingTestEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/MappingTestsExplorer.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionQueryEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/mapping/MappingTestState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceExecutionState.ts
  packages/legend-application-studio/style/components/editor/_service-editor.scss
  packages/legend-application-studio/style/components/editor/mapping-editor/_mapping-test-editor.scss
  packages/legend-application-studio/style/components/editor/mapping-editor/_mapping-test-explorer.scss
Labels: cla-present

#1383 Alert user changing fetch structure resets state
  .changeset/itchy-chairs-pay.md
  packages/legend-application-query/src/components/QueryBuilderFetchStructurePanel.tsx
Labels: cla-present

#1359 Block certain actions when query is not valid
  .changeset/fast-spiders-flow.md
  packages/legend-application-query/src/components/QueryBuilderResultPanel.tsx
  packages/legend-application-query/src/stores/QueryBuilderProjectionState.ts
  packages/legend-application-query/src/stores/QueryBuilderState.ts
  packages/legend-application-query/style/_query-builder.scss
Labels: cla-present

#1336 Check type compability when dragging and dropping parameters into filter/post filter
  .changeset/green-mails-shake.md
  packages/legend-application-query/src/components/QueryBuilderFilterPanel.tsx
  packages/legend-application-query/src/components/QueryBuilderPostFilterPanel.tsx
  packages/legend-application-query/src/stores/QueryBuilderOperatorsHelper.ts
  packages/legend-application-query/src/stores/filterOperators/QueryBuilderFilterOperator_Equal.ts
  packages/legend-application-query/src/stores/filterOperators/QueryBuilderFilterOperator_GreaterThan.ts
  packages/legend-application-query/src/stores/filterOperators/QueryBuilderFilterOperator_GreaterThanEqual.ts
  packages/legend-application-query/src/stores/filterOperators/QueryBuilderFilterOperator_LessThan.ts
  packages/legend-application-query/src/stores/filterOperators/QueryBuilderFilterOperator_LessThanEqual.ts
  packages/legend-application-query/src/stores/postFilterOperators/QueryBuilderPostFilterOperator_Equal.ts
  packages/legend-application-query/src/stores/postFilterOperators/QueryBuilderPostFilterOperator_GreaterThan.ts
  packages/legend-application-query/src/stores/postFilterOperators/QueryBuilderPostFilterOperator_LessThan.ts
Labels: cla-present, Component: Query Builder

#1384 minor fixes
  .changeset/slow-clouds-look.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/ServiceRegistrationTest.test.tsx
  packages/legend-application-studio/src/components/workspace-setup/WorkspaceSetup.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceRegistrationState.ts
Labels: cla-present

#1364 FlatData: Handle multi-date formats
  .changeset/sweet-plants-trade.md
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/flatData/model/FlatDataDataType.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/flatData/model/FlatDataProperty.ts
  packages/legend-graph/src/graphManager/__tests__/roundtripTestData/TEST_DATA__FlatDataRoundtrip.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/flatData/model/V1_FlatDataDataType.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/flatData/model/V1_FlatDataProperty.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_FlatDataStoreBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_StoreSerializationHelper.ts
  packages/legend-shared/src/application/HashUtils.ts
Labels: cla-present

#1386 query builder: show UI error when there are no projections in query builder
  .changeset/cyan-yaks-wonder.md
  .changeset/nine-shirts-run.md
  packages/legend-application-query/src/components/QueryBuilderProjectionPanel.tsx
  packages/legend-application-query/src/components/QueryBuilderResultPanel.tsx
  packages/legend-application-query/src/stores/QueryBuilderProjectionState.ts
  packages/legend-application-query/style/_query-builder-projection.scss
Labels: cla-present

#1370 feat: add visual indicator for system elements in selector dropdowns
  .changeset/chilled-timers-peel.md
  .changeset/clever-phones-travel.md
  packages/legend-application-query/src/components/QueryBuilderFunctionsExplorerPanel.tsx
  packages/legend-application-query/src/components/QueryBuilderParameterPanel.tsx
  packages/legend-application-query/src/components/QueryBuilderSetupPanel.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/NewMappingElementModal.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/ClassEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/CreateNewElementModal.tsx
  packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
  packages/legend-application/src/components/shared/PackageableElementOptionRenderer.tsx
  packages/legend-application/style/components/shared/_packageable-element-format-option.scss
  packages/legend-art/style/base/_variables.scss
  packages/legend-graph/src/graphManager/GraphManagerState.ts
Labels: cla-present

#1381 query-builder: typeahead for filter and post-filter
  .changeset/fire-fire-lobster.md
  .changeset/smart-cake.md
  .changeset/smart-pumpkins-unite.md
  packages/legend-application-query/src/components/QueryBuilderFetchStructurePanel.tsx
  packages/legend-application-query/src/components/QueryBuilderFilterPanel.tsx
  packages/legend-application-query/src/components/QueryBuilderPostFilterPanel.tsx
  packages/legend-application-query/src/components/__tests__/QueryBuilder_FetchStructure.test.tsx
  packages/legend-application-query/src/stores/QueryBuilderFetchStructureState.ts
  packages/legend-application-query/src/stores/QueryBuilderFilterState.ts
  packages/legend-application-query/src/stores/QueryBuilderOperatorLoader.ts
  packages/legend-application-query/src/stores/QueryBuilderPostFilterState.ts
  packages/legend-application-query/src/stores/QueryBuilderPreviewDataHelper.ts
  packages/legend-application-query/src/stores/QueryBuilderProjectionState.ts
  packages/legend-application-query/src/stores/QueryBuilderState.ts
  packages/legend-application-query/src/stores/QueryBuilderTestUtils.ts
  packages/legend-application-query/src/stores/QueryBuilderTypeaheadHelper.ts
  packages/legend-application-query/src/stores/__tests__/QueryBuilder_PreviewData.test.ts
  packages/legend-application-query/src/stores/__tests__/QueryBuilder_Typeahead.test.ts
  packages/legend-application-query/src/stores/__tests__/TEST_DATA__QueryBuilder_PreviewDataTest.ts
  packages/legend-application-query/src/stores/__tests__/TEST_DATA__QueryBuilder_PropertySearch.ts
  packages/legend-application-query/src/stores/__tests__/TEST_DATA__QueryBuilder_TestTypeaheadSearch.ts
  packages/legend-application/src/components/shared/BasicValueSpecificationEditor.tsx
  packages/legend-art/src/components/CJS__ReactSelect.cts
  packages/legend-art/src/components/CustomSelectorInput.tsx
Labels: cla-present

#1397 Revert "flat-data: handle multi-date formats
  .changeset/good-pots-wonder.md
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/flatData/model/FlatDataDataType.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/flatData/model/FlatDataProperty.ts
  packages/legend-graph/src/graphManager/__tests__/roundtripTestData/TEST_DATA__FlatDataRoundtrip.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/flatData/model/V1_FlatDataDataType.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/flatData/model/V1_FlatDataProperty.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_FlatDataStoreBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_StoreSerializationHelper.ts
  packages/legend-shared/src/application/HashUtils.ts
Labels: cla-present

#1395 feat: allow DnD to rearrange properties/supertypes/etc
  .changeset/poor-stingrays-dance.md
  .changeset/tame-moles-call.md
  packages/legend-application-query/src/components/QueryBuilderProjectionPanel.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/FunctionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/GenerationSpecificationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/data-editor/DataElementEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/AssociationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/ClassEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/EnumerationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/ProfileEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/PropertyEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/StereotypeSelector.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/TaggedValueEditor.tsx
  packages/legend-application-studio/src/stores/graphModifier/DomainGraphModifierHelper.ts
  packages/legend-application-studio/style/components/editor/uml-editor/_class-editor.scss
  packages/legend-application-studio/style/components/editor/uml-editor/_uml-element-editor.scss
  packages/legend-graph/src/graph/metamodel/pure/Reference.ts
  packages/legend-shared/src/CommonUtils.ts
Labels: cla-present

#1408 post filter and parameter panel minor improvement
  .changeset/silver-bulldogs-rest.md
  packages/legend-application-query/src/components/QueryBuilder.tsx
  packages/legend-application-query/src/components/QueryBuilderProjectionPanel.tsx
Labels: cla-present

#1412 Fix a bug where there is a false-positive change detection for propertyMapping without ID
  .changeset/nervous-lemons-play.md
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/mapping/PropertyMapping.ts
Labels: cla-present

#1415 gh: add milestoned issues to project
  .github/workflows/bot__new-issue-label copy.yml
  scripts/github-bot/addMilestonedIssueToProject.js
Labels: cla-present

#1416 gh: add milestoned issues to project (part 2)
  .github/workflows/bot__new-issue-track.yml
  scripts/github-bot/trackNewMilestonedIssue.js
Labels: cla-present

#1417 gh: add milestoned issues to project (part 3)
  scripts/github-bot/package.json
  scripts/github-bot/trackNewMilestonedIssue.js
  yarn.lock
Labels: cla-present

#1418 gh: add milestoned issues to project (part 4)
  .github/workflows/bot__new-issue-track.yml
Labels: cla-present

#1419 gh: add milestoned issues to project (part 5)
  .changeset/rich-dragons-greet.md
  packages/legend-art/style/base/_common.scss
  scripts/github-bot/trackNewMilestonedIssue.js
Labels: cla-present

#1420 gh: add milestoned issues to project (part 6)
  scripts/github-bot/trackNewMilestonedIssue.js
Labels: cla-present

#1405 add sdlc server to legend query application
  .changeset/shot-tails-high.md
  .changeset/tall-colts-wait.md
  packages/legend-application-query-bootstrap/scripts/setup.js
  packages/legend-application-query/package.json
  packages/legend-application-query/src/application/LegendQueryApplicationConfig.ts
  packages/legend-application-query/src/components/LegendQueryApplication.tsx
  packages/legend-application-query/src/components/LegendQueryBaseStoreProvider.tsx
  packages/legend-application-query/src/components/QueryEditorComponentTestUtils.tsx
  packages/legend-application-query/src/components/QueryEditorStoreProvider.tsx
  packages/legend-application-query/src/components/QuerySetupStoreProvider.tsx
  packages/legend-application-query/src/stores/LegendQueryBaseStore.ts
  packages/legend-application-query/src/stores/QueryEditorStore.ts
  packages/legend-application-query/src/stores/QueryEditorStoreTestUtils.ts
  packages/legend-application-query/src/stores/QuerySetupStore.ts
  packages/legend-application-query/tsconfig.build.json
  packages/legend-application-query/tsconfig.json
  packages/legend-application-studio/src/components/LegendStudioApplication.tsx
  packages/legend-application-studio/src/stores/LegendStudioBaseStore.ts
  packages/legend-application/package.json
  packages/legend-application/src/index.ts
  packages/legend-application/src/stores/LegendApplicationSDLCSetupState.ts
  packages/legend-application/tsconfig.build.json
  packages/legend-application/tsconfig.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-data-space/src/components/query/DataSpaceQueryEditor.tsx
  packages/legend-extension-dsl-data-space/src/stores/query/DataSpaceQueryEditorStore.ts
  packages/legend-extension-dsl-data-space/tsconfig.build.json
  packages/legend-extension-dsl-data-space/tsconfig.json
  packages/legend-server-sdlc/src/SDLCServerClientTestUtils.tsx
  yarn.lock
Labels: cla-present

#1421 Fix a regression introduced for milestoning in #1388
  .changeset/chilly-ducks-rest.md
  packages/legend-extension-application-studio-query-builder/src/components/QueryBuilder_LegendStudioApplicationPlugin.tsx
Labels: cla-present, Type: Regression, Component: Query Builder

#1407 Flat-data: handle multi-date formats
  .changeset/sweet-plants-trade.md
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/flatData/model/FlatDataDataType.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/flatData/model/FlatDataProperty.ts
  packages/legend-graph/src/graphManager/__tests__/roundtripTestData/TEST_DATA__FlatDataRoundtrip.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/flatData/model/V1_FlatDataDataType.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/flatData/model/V1_FlatDataProperty.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_FlatDataStoreBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_StoreSerializationHelper.ts
Labels: cla-present, Status: Waiting for Backend Change

#1238 Support middle-tier authentication strategy
  .changeset/curly-houses-act.md
  .changeset/tidy-rabbits-cover.md
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/RelationalDatabaseConnectionEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/connection/ConnectionEditorState.ts
  packages/legend-application-studio/src/stores/graphModifier/StoreRelational_GraphModifierHelper.ts
  packages/legend-graph/src/graph/Core_HashUtils.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/relational/connection/AuthenticationStrategy.ts
  packages/legend-graph/src/graphManager/__tests__/roundtripTestData/TEST_DATA__RelationalRoundtrip.ts
  packages/legend-graph/src/graphManager/action/changeDetection/StoreRelational_ObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/relational/connection/V1_AuthenticationStrategy.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_ConnectionTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_RelationalConnectionBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_ConnectionSerializationHelper.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/relational-connection.pure
Labels: cla-present, Status: Waiting for Backend Change

#1423 Fix propagating of default date for milestoned properties from association
  .changeset/strange-pumas-cheat.md
  packages/legend-application-query/src/stores/QueryBuilderPropertyEditorState.ts
  packages/legend-graph/src/graph/helpers/DomainHelper.ts
Labels: cla-present

#1429 minor improvements to service test editor
  .changeset/quick-horses-jog.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestDataEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestDataState.ts
  packages/legend-application-studio/src/stores/shared/testable/TestableUtils.ts
  packages/legend-application-studio/style/components/editor/_service-editor.scss
Labels: cla-present

#1428 Fix a bug where default value of `date` type will throw a cast error for parameter
  .changeset/light-falcons-speak.md
  .changeset/sour-plums-heal.md
  packages/legend-application-query/src/components/QueryBuilderParameterPanel.tsx
  packages/legend-application-query/src/stores/QueryBuilderLambdaProcessor.ts
  packages/legend-application-query/src/stores/QueryBuilderState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceExecutionState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestEditorState.ts
  packages/legend-application/src/stores/shared/LambdaParameterState.ts
  packages/legend-graph/src/graph/helpers/ValueSpecificationHelper.ts
Labels: cla-present

#1401 cleanup
  .changeset/tame-rules-try.md
  packages/legend-application-query/src/components/QueryBuilderFetchStructurePanel.tsx
  packages/legend-application-query/src/stores/QueryBuilderFetchStructureState.ts
  packages/legend-application-query/src/stores/QueryBuilderFilterState.ts
  packages/legend-application-query/src/stores/QueryBuilderOperatorLoader.ts
  packages/legend-application-query/src/stores/QueryBuilderPostFilterState.ts
  packages/legend-application-query/src/stores/QueryBuilderProjectionState.ts
  packages/legend-application-query/src/stores/QueryBuilderState.ts
  packages/legend-application-query/src/stores/QueryBuilderTypeaheadHelper.ts
  packages/legend-application-query/src/stores/__tests__/QueryBuilder_Typeahead.test.ts
Labels: cla-present

#1425 Support creation of self-referenced associations in form mode
  .changeset/itchy-toes-behave.md
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/AssociationEditor.tsx
Labels: cla-present

#1432 Model Import External Formats
  .changeset/more-binding-test.md
  .changeset/real-buses-invite.md
  .changeset/three-wolves-hunt.md
  .github/ISSUE_TEMPLATE/Bug_report.yml
  packages/legend-application-studio/src/components/EditorComponentTestUtils.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/EditPanel.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/ModelImporter.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/ModelLoader.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/external-format-editor/SchemaSetElementEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/external-format-editor/SchemaSetModelGenerationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/ServiceRegistrationTest.test.tsx
  packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
  packages/legend-application-studio/src/components/editor/side-bar/__tests__/CreateNewElement.test.tsx
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/EditorStore.ts
  packages/legend-application-studio/src/stores/LegendStudioApplicationPlugin.ts
  packages/legend-application-studio/src/stores/editor-state/ExternalFormatState.ts
  packages/legend-application-studio/src/stores/editor-state/ModelImporterState.ts
  packages/legend-application-studio/src/stores/editor-state/ModelLoaderState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/external-format/SchemaSetEditorState.ts
  packages/legend-application-studio/src/stores/graphModifier/DSLExternalFormat_GraphModifierHelper.ts
  packages/legend-graph/src/graphManager/AbstractPureGraphManager.ts
  packages/legend-graph/src/graphManager/action/generation/ImportConfigurationDescription.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/V1_Engine.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/V1_EngineHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/V1_EngineServerClient.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/externalFormat/V1_ExternalFormatModelGeneration.ts
  packages/legend-graph/src/index.ts
Labels: cla-present

#1439 Fix a bug that fails to display subtypes if a propertyMapping of type parent directly points to a child classMapping
  .changeset/smart-tigers-watch.md
  packages/legend-application-query/src/stores/explorer/QueryBuilderExplorerState.ts
Labels: cla-present

#1445 fix model importer extension post https://github.com/finos/legend-studio/pull/1432
  .changeset/soft-pandas-press.md
  .changeset/stupid-icons-wonder.md
  fixtures/legend-mock-server/package.json
  package.json
  packages/babel-preset/package.json
  packages/eslint-plugin/package.json
  packages/legend-application-query-bootstrap/package.json
  packages/legend-application-query-deployment/package.json
  packages/legend-application-query/package.json
  packages/legend-application-studio-bootstrap/package.json
  packages/legend-application-studio-deployment/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-studio/src/components/editor/edit-panel/ModelImporter.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/NewMappingElementModal.tsx
  packages/legend-application-studio/src/index.ts
  packages/legend-application-studio/src/stores/LegendStudioApplicationPlugin.ts
  packages/legend-application-studio/src/stores/editor-state/ModelImporterState.ts
  packages/legend-application-studio/src/stores/editor-state/entity-diff-editor-state/EntityChangeConflictEditorState.ts
  packages/legend-application-taxonomy-bootstrap/package.json
  packages/legend-application-taxonomy-deployment/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-extension-application-studio-management-toolkit/package.json
  packages/legend-extension-application-studio-query-builder/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-external-format-json-schema/package.json
  packages/legend-extension-external-language-morphir/package.json
  packages/legend-extension-external-store-service/package.json
  packages/legend-extension-tracer-zipkin/package.json
  packages/legend-graph/package.json
  packages/legend-manual-tests/package.json
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-storage/package.json
  packages/stylelint-config/package.json
  scripts/typedoc-theme/package.json
  yarn.lock
Labels: cla-present

#1367 Highlight already used properties in explorer tree of query builder
  .changeset/many-mails-learn.md
  .changeset/perfect-pigs-laugh.md
  packages/legend-application-query/src/components/explorer/QueryBuilderExplorerPanel.tsx
  packages/legend-application-query/src/stores/__tests__/QueryBuilder_ExplorerState.test.ts
  packages/legend-application-query/src/stores/__tests__/TEST_DATA__ModelCoverageAnalysisResult.ts
  packages/legend-application-query/src/stores/__tests__/TEST_DATA__QueryBuilder_HighlightProperties.ts
  packages/legend-application-query/src/stores/__tests__/TEST_DATA__QueryBuilder_Model_ComplexSubType.json
  packages/legend-application-query/src/stores/__tests__/TEST_DATA__QueryBuilder_Model_HiglightProperties.json
  packages/legend-application-query/src/stores/explorer/QueryBuilderExplorerState.ts
  packages/legend-application-query/src/stores/fetch-structure/graph-fetch/QueryBuilderGraphFetchTreeUtil.ts
  packages/legend-application-query/src/stores/fetch-structure/projection/QueryBuilderProjectionState.ts
  packages/legend-application-query/style/_query-builder-explorer.scss
Labels: cla-present

#1448 minor fixes
  .changeset/nice-colts-cover.md
  packages/legend-application-studio/src/index.ts
  packages/legend-application-studio/src/stores/editor-state/ModelImporterState.ts
Labels: cla-present

#1449 bump dependencies
  .changeset/nervous-peas-tan.md
  fixtures/legend-mock-server/package.json
  package.json
  packages/babel-preset/package.json
  packages/legend-application-query-bootstrap/package.json
  packages/legend-application-query-deployment/package.json
  packages/legend-application-query/package.json
  packages/legend-application-studio-bootstrap/package.json
  packages/legend-application-studio-deployment/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-taxonomy-bootstrap/package.json
  packages/legend-application-taxonomy-deployment/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-extension-application-studio-management-toolkit/package.json
  packages/legend-extension-application-studio-query-builder/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-external-format-json-schema/package.json
  packages/legend-extension-external-language-morphir/package.json
  packages/legend-extension-external-store-service/package.json
  packages/legend-extension-tracer-zipkin/package.json
  packages/legend-graph/package.json
  packages/legend-manual-tests/package.json
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-storage/package.json
  packages/stylelint-config/package.json
  scripts/typedoc-theme/package.json
  yarn.lock
Labels: cla-present

#1454 add full interactive light
  .changeset/dry-chairs-enjoy.md
  .changeset/six-lions-thank.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/ServiceRegistrationTest.test.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceEditorState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceRegistrationState.ts
  packages/legend-graph/src/graphManager/action/service/ServiceExecutionMode.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/V1_Engine.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/V1_EngineServerClient.ts
Labels: cla-present
