Repository finos/legend-studio, pull requests merged in 2022-12, with the labels that each got.

#1740 View dependency SDLC project with selected version
  .changeset/rich-gorillas-speak.md
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectConfigurationEditor.tsx
Labels: cla-present

#1739 support service postValidations part I - fix broken tests related to service postValidation
  .changeset/hot-lamps-confess.md
  packages/legend-graph/src/graph/Core_HashUtils.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/service/PostValidation.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/service/PostValidationAssertion.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/service/Service.ts
  packages/legend-graph/src/graphManager/action/changeDetection/DSL_Service_ObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/service/V1_PostValidation.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/service/V1_PostValidationAssertion.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/service/V1_Service.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_ServiceTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/V1_ElementSecondPassBuilder.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_ServiceBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_ServiceSerializationHelper.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/DSL_Service-with-postValidation.pure
Labels: cla-present

#1736 Add default serialization format for service tests
  .changeset/yellow-pandas-glow.md
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestEditorState.ts
Labels: cla-present

#1570 add support of text mode for services with only query
  .changeset/breezy-pumas-own.md
  .changeset/red-crabs-vanish.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionQueryEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestableEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceEditorState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceExecutionState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestDataState.ts
  packages/legend-application-studio/src/stores/shared/modifier/DSL_Service_GraphModifierHelper.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/service/ServiceExecution.ts
  packages/legend-graph/src/graphManager/__tests__/ImportResolutionRoundtrip.test.ts
  packages/legend-graph/src/graphManager/__tests__/roundtripTestData/TEST_DATA__ServiceRoundtrip.ts
  packages/legend-graph/src/graphManager/action/changeDetection/DSL_Service_ObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/service/V1_ServiceExecution.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_ServiceTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_ServiceBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_ServiceSerializationHelper.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/DSL_Service-withOnlyQuery.pure
  packages/legend-query-builder/src/stores/workflows/ServiceQueryBuilderState.ts
Labels: cla-present

#1755 dependency tree improvements
  .changeset/more-swift-eat.md
  .changeset/swift-moles-eat.md
  packages/legend-application-studio/src/components/EditorComponentTestUtils.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/__tests__/ProjectConfigurationEditor.test.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectConfigurationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectDependencyEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/ServiceRegistrationTest.test.tsx
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/__tests__/ProjectDependencyManager.test.ts
  packages/legend-application-studio/src/stores/editor-state/ProjectConfigurationEditorState.ts
  packages/legend-application-studio/style/components/editor/_project-configuration-editor.scss
  packages/legend-server-depot/src/DepotServerClient.ts
  packages/legend-server-depot/src/ProjectDependencyGraphReportHelper.ts
  packages/legend-server-depot/src/index.ts
  packages/legend-server-depot/src/models/ProjectDependencyGraph.ts
  packages/legend-server-depot/src/models/RawProjectDependencyReport.ts
Labels: cla-present

#1756 bump dependencies
  .changeset/red-lemons-float.md
  fixtures/legend-mock-server/package.json
  package.json
  packages/babel-preset/package.json
  packages/eslint-plugin/package.json
  packages/legend-application-pure-ide-deployment/package.json
  packages/legend-application-pure-ide/package.json
  packages/legend-application-query-bootstrap/package.json
  packages/legend-application-query-deployment/package.json
  packages/legend-application-query/package.json
  packages/legend-application-studio-bootstrap/package.json
  packages/legend-application-studio-deployment/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-taxonomy-bootstrap/package.json
  packages/legend-application-taxonomy-deployment/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-mastery/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-service/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-format-json-schema/package.json
  packages/legend-extension-format-morphir/package.json
  packages/legend-extension-store-flat-data/package.json
  packages/legend-extension-store-relational/package.json
  packages/legend-extension-store-service-store/package.json
  packages/legend-extension-tracer-zipkin/package.json
  packages/legend-graph/package.json
  packages/legend-manual-tests/package.json
  packages/legend-query-builder/package.json
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-storage/package.json
  packages/stylelint-config/package.json
  scripts/github-bot/package.json
  scripts/typedoc-theme/package.json
  yarn.lock
Labels: cla-present

#1754 Send unitTestId as a part of payload when we generate service test expected result
  .changeset/mighty-carrots-appear.md
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
Labels: cla-present, Extension: DSL Service, Component: Testing

#1760 minor config editor cleanups
  .changeset/ten-donkeys-grab.md
  packages/legend-application-studio/src/components/editor/edit-panel/EditPanel.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/__tests__/ProjectConfigurationEditor.test.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectConfigurationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectDependencyEditor.tsx
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/EditorStore.ts
  packages/legend-application-studio/src/stores/EditorTabManagerState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestDataState.ts
  packages/legend-application-studio/src/stores/editor-state/project-configuration-editor-state/ProjectConfigurationEditorState.ts
  packages/legend-application-studio/src/stores/editor-state/project-configuration-editor-state/ProjectDependencyEditorState.ts
  packages/legend-query-builder/src/stores/workflows/ServiceQueryBuilderState.ts
Labels: cla-present

#1762 Fix regression introduced for service test editor in #1570
  .changeset/rude-spoons-mix.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestableEditor.tsx
Labels: cla-present, Type: Regression

#1761 Modify save and generate option buttons for database builder
  .changeset/fast-points-decide.md
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/DatabaseBuilder.tsx
  packages/legend-application-studio/style/components/editor/_database-builder.scss
Labels: cla-present

#1769 minor fixes
  .changeset/moody-toes-impress.md
  packages/eslint-plugin/package.json
  packages/legend-application-pure-ide/src/components/editor/edit-panel/PureFileEditor.tsx
  packages/legend-application-pure-ide/src/components/editor/side-bar/CreateNewDirectoryPrompt.tsx
  packages/legend-application-pure-ide/src/components/editor/side-bar/CreateNewFilePrompt.tsx
  packages/legend-application-pure-ide/src/components/editor/side-bar/MoveElementPrompt.tsx
  packages/legend-application-pure-ide/src/components/editor/side-bar/RenameConceptPrompt.tsx
  packages/legend-application-pure-ide/src/components/editor/side-bar/RenameFilePrompt.tsx
  packages/legend-application-pure-ide/src/stores/FileEditorState.ts
  packages/legend-application/src/const.ts
  packages/legend-dev-utils/WebpackConfigUtils.js
  packages/legend-shared/package.json
  packages/legend-shared/src/network/NetworkUtils.ts
  scripts/test/jest.config.base.js
  yarn.lock
Labels: cla-present

#1773 bump dependencies and fix yarn.lock
  .changeset/silver-jobs-poke.md
  package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-shared/package.json
  yarn.lock
Labels: cla-present

#1753 Fix a bug with PackageableTreeNode not getting selected for dependency elements
  .changeset/forty-onions-pretend.md
  packages/legend-application-studio/src/stores/shared/PackageTreeUtils.ts
Labels: cla-present

#1775 fix: model importer tab behavior
  .changeset/doubtful-dodos-dawdle.md
  packages/legend-application-studio/src/stores/editor-state/ModelImporterState.ts
Labels: cla-present, Type: Bug, Application: Studio

#1777 fix debouncing generate function in xt format model generaiton
  .changeset/proud-fireants-listen.md
  packages/legend-application-studio/src/components/editor/edit-panel/external-format-editor/DSL_ExternalFormat_SchemaSetModelGenerationEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/FileGenerationState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/external-format/DSL_ExternalFormat_SchemaSetEditorState.ts
  packages/legend-application-studio/src/stores/shared/modifier/DSL_Generation_GraphModifierHelper.ts
  packages/legend-application-studio/style/components/editor/_file-generation-editor.scss
Labels: cla-present

#1766 Add service store con snippet and editor support
  .changeset/loud-worms-teach.md
  .changeset/mean-ghosts-double.md
  packages/legend-application-studio/src/components/DSL_ExternalFormat_LegendStudioApplicationPlugin.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/GrammarTextEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/external-format-editor/DSL_ExternalFormat_ExternalFormatConnectionEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/CreateNewElementModal.tsx
  packages/legend-application-studio/src/stores/DSL_Mapping_LegendStudioApplicationPlugin_Extension.ts
  packages/legend-application-studio/src/stores/editor/NewElementState.ts
  packages/legend-extension-store-service-store/src/components/STO_ServiceStore_CodeSnippets.ts
  packages/legend-extension-store-service-store/src/components/STO_ServiceStore_LegendStudioApplicationPlugin.tsx
  packages/legend-extension-store-service-store/src/components/ServiceStoreElementEditor.tsx
  packages/legend-extension-store-service-store/src/graphManager/STO_ServiceStore_PureGraphManagerPlugin.ts
  packages/legend-extension-store-service-store/src/stores/studio/STO_ServiceStore_GraphModifierHelper.ts
  packages/legend-extension-store-service-store/style/index.scss
Labels: cla-present

#1774 Pure IDE: improve contextual auto-complete/suggestion support
  .changeset/calm-tigers-dance.md
  .changeset/chilly-eagles-yawn.md
  packages/legend-application-pure-ide/src/components/editor/edit-panel/PureFileEditor.tsx
  packages/legend-application-pure-ide/src/components/editor/side-bar/ConceptTreeExplorer.tsx
  packages/legend-application-pure-ide/src/components/editor/side-bar/DirectoryTreeExplorer.tsx
  packages/legend-application-pure-ide/src/server/PureServerClient.ts
  packages/legend-application-pure-ide/src/server/models/ConceptTree.ts
  packages/legend-application-pure-ide/src/server/models/Suggestion.ts
  packages/legend-application-pure-ide/src/stores/FileEditorState.ts
  packages/legend-application-pure-ide/src/stores/FileEditorUtils.ts
  packages/legend-application-pure-ide/src/stores/PureFileEditorUtils.ts
  packages/legend-application/src/stores/PureLanguageSupport.ts
  packages/legend-art/src/utils/TextEditorUtils.ts
  packages/legend-art/style/reset/_react-reflex.scss
Labels: cla-present

#1693 Remove graph building form text mode
  .changeset/honest-dolphins-beg.md
  packages/legend-application-studio/src/components/editor/side-bar/LocalChanges.tsx
  packages/legend-application-studio/src/stores/ChangeDetectionState.ts
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/EditorStore.ts
  packages/legend-application-studio/src/stores/EditorTabManagerState.ts
  packages/legend-application-studio/src/stores/ExplorerTreeState.ts
  packages/legend-application-studio/src/stores/editor-state/FileGenerationViewerState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/ElementEditorState.ts
  packages/legend-application-studio/src/stores/sidebar-state/LocalChangesState.ts
  packages/legend-graph/src/graphManager/AbstractPureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
Labels: cla-present

#1784 Fix regression introduced for explorer tree building in #1693
  .changeset/six-pandas-cheer.md
  packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/ExplorerTreeState.ts
Labels: cla-present, Type: Regression

#1790 bump dependencies
  .changeset/sour-ducks-breathe.md
  .github/ISSUE_TEMPLATE/Bug_report.yml
  .github/ISSUE_TEMPLATE/Feature_request.yml
  fixtures/legend-mock-server/package.json
  package.json
  packages/babel-preset/package.json
  packages/eslint-plugin/package.json
  packages/legend-application-pure-ide-deployment/package.json
  packages/legend-application-pure-ide/package.json
  packages/legend-application-pure-ide/src/components/editor/edit-panel/PureFileEditor.tsx
  packages/legend-application-query-bootstrap/package.json
  packages/legend-application-query-deployment/package.json
  packages/legend-application-query/package.json
  packages/legend-application-studio-bootstrap/package.json
  packages/legend-application-studio-deployment/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-taxonomy-bootstrap/package.json
  packages/legend-application-taxonomy-deployment/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-mastery/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-service/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-format-json-schema/package.json
  packages/legend-extension-format-morphir/package.json
  packages/legend-extension-store-flat-data/package.json
  packages/legend-extension-store-relational/package.json
  packages/legend-extension-store-service-store/package.json
  packages/legend-extension-tracer-zipkin/package.json
  packages/legend-graph/package.json
  packages/legend-manual-tests/package.json
  packages/legend-manual-tests/src/__tests__/ProfilingGraphBuilding.test.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar-mismatch/RoundtripGrammarMismatch.test.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/RoundtripGrammar.test.ts
  packages/legend-query-builder/package.json
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-storage/package.json
  packages/stylelint-config/package.json
  scripts/test/jest.config.base.js
  scripts/typedoc-theme/package.json
  yarn.lock
Labels: cla-present

#1789 Fix a bug with unable to open file generation tree data after hitting F10
  .changeset/cuddly-bobcats-dance.md
  packages/legend-application-studio/src/stores/editor-state/GraphGenerationState.ts
Labels: cla-present, Extension: DSL Generation

#1791 enhance dependency explorer and add tree view for dependency conflicts
  .changeset/neat-peas-water.md
  .changeset/neat-peas-wave.md
  packages/legend-application-studio/src/components/editor/edit-panel/__tests__/ProjectConfigurationEditor.test.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/__tests__/ProjectDependencyConflictViewer.test.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/__tests__/ProjectDependencyEditor.test.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/__tests__/TEST_DATA__ProjectDependencyInfo.ts
  packages/legend-application-studio/src/components/editor/edit-panel/__tests__/TEST_DATA__ProjectDependencyReport.ts
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectDependencyEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/ServiceEditorTest.test.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/ServiceRegistrationTest.test.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/TEST_DATA__ServiceEditor.ts
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/TEST_DATA__ServiceRegistration.json
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/LegendStudioRouter.ts
  packages/legend-application-studio/src/stores/__tests__/ProjectDependencyManager.test.ts
  packages/legend-application-studio/src/stores/editor-state/project-configuration-editor-state/ProjectDependencyEditorState.ts
  packages/legend-application-studio/style/components/editor/_project-configuration-editor.scss
  packages/legend-art/src/components/CJS__Icon.cts
  packages/legend-server-depot/src/ProjectDependencyGraphReportHelper.ts
  packages/legend-server-depot/src/models/ProjectDependencyGraph.ts
Labels: cla-present

#1788 minor cleanups post #1693 and #1784
  .changeset/loud-frogs-grab.md
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/EditorStore.ts
  packages/legend-application-studio/src/stores/EditorTabManagerState.ts
  packages/legend-application-studio/src/stores/ExplorerTreeState.ts
  packages/legend-application-studio/src/stores/project-viewer/ProjectViewerStore.ts
  packages/legend-application-studio/src/stores/sidebar-state/LocalChangesState.ts
Labels: cla-present

#1794 Pure IDE: more improvements
  .changeset/brave-rivers-argue.md
  .changeset/flat-glasses-unite.md
  .changeset/popular-glasses-exist.md
  .github/workflows/check-code.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  jest.config.js
  package.json
  packages/babel-preset/package.json
  packages/eslint-plugin/package.json
  packages/legend-application-pure-ide/src/components/editor/edit-panel/PureFileEditor.tsx
  packages/legend-application-pure-ide/src/components/editor/side-bar/DirectoryTreeExplorer.tsx
  packages/legend-application-pure-ide/src/server/PureServerClient.ts
  packages/legend-application-pure-ide/src/server/models/File.ts
  packages/legend-application-pure-ide/src/server/models/Suggestion.ts
  packages/legend-application-pure-ide/src/stores/EditorStore.ts
  packages/legend-application-pure-ide/src/stores/EditorTabManagerState.ts
  packages/legend-application-pure-ide/src/stores/FileEditorState.ts
  packages/legend-application-pure-ide/src/stores/PureFileEditorUtils.ts
  packages/legend-application-pure-ide/style/components/editor/_edit-panel.scss
  packages/legend-application-studio/src/stores/editor-state/project-configuration-editor-state/ProjectDependencyEditorState.ts
  packages/legend-application/src/components/shared/TabManager.tsx
  packages/legend-application/src/stores/PureLanguageSupport.ts
  packages/legend-application/src/stores/PureLanguageTextEditorSupport.ts
  packages/legend-dev-utils/JestConfigUtils.js
  packages/legend-dev-utils/package.json
  packages/legend-shared/package.json
  scripts/test/jest.config.base.js
  yarn.lock
Labels: cla-present

#1793 fix clearing generation entities
  .changeset/twelve-kangaroos-jump.md
  packages/legend-application-studio/src/components/editor/StatusBar.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/GenerationSpecificationEditor.tsx
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/editor-state/GraphGenerationState.ts
Labels: cla-present

#1801 Fix global test runner not showing status of test run for services with multi execution
  .changeset/mighty-dragons-roll.md
  packages/legend-application-studio/src/components/editor/side-bar/testable/GlobalTestRunner.tsx
  packages/legend-application-studio/src/stores/sidebar-state/testable/GlobalTestRunnerState.ts
Labels: cla-present

#1802 fix multi execution service test + minor cleanups in exec state
  .changeset/cyan-comics-laugh.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/ServiceEditorTest.test.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceExecutionState.ts
Labels: cla-present

#1803 enable testing and execution via service editor for inline queries
  .changeset/another-bug-lick.md
  .changeset/blue-ladybugs-lick.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionQueryEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestableEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/mapping/MappingExecutionState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/mapping/MappingTestState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceExecutionState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestEditorState.ts
  packages/legend-graph/src/graphManager/AbstractPureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/DSL_ExternalFormat_PureProtocolProcessorPlugin.ts
  packages/legend-graph/src/graphManager/protocol/pure/PureProtocolProcessorPlugin.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/execution/V1_ExecuteInput.ts
  packages/legend-query-builder/src/stores/QueryBuilderResultState.ts
  packages/legend-query-builder/src/stores/explorer/QueryBuilderExplorerState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/QueryBuilderPostFilterState.ts
  packages/legend-query-builder/src/stores/filter/QueryBuilderFilterState.ts
Labels: cla-present

#1804 bump dependencies
  .changeset/funny-teachers-shave.md
  README.md
  package.json
  packages/eslint-plugin/package.json
  packages/legend-application-pure-ide/package.json
  packages/legend-application-query/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-query-builder/package.json
  yarn.lock
Labels: cla-present
