Repository finos/legend-studio, pull requests merged in 2023-01, with the labels that each got.

#1730 Improve query execution test flow
  .changeset/loud-kids-wait.md
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/index.ts
  packages/legend-manual-tests/package.json
  packages/legend-manual-tests/src/__tests__/query-execution/QueryBuilderExecution.test.tsx
  packages/legend-manual-tests/src/__tests__/query-execution/TEST_DATA_QueryBuilder_QueryExecution_Entities.json
  packages/legend-manual-tests/src/__tests__/query-execution/TEST_DATA_QueryBuilder_Query_Execution.ts
  packages/legend-manual-tests/tsconfig.json
  packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilder_TestID.ts
  packages/legend-query-builder/src/components/__tests__/QueryBuilderExecution.test.tsx
  packages/legend-query-builder/src/index.ts
  yarn.lock
Labels: cla-present

#1685 Support a searchable dropdown when adding service owners
  .changeset/bright-turtles-promise.md
  .changeset/twelve-pugs-sing.md
  .changeset/warm-badgers-run.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/__tests__/ServiceRegistrationTest.test.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceEditorState.ts
  packages/legend-application-studio/style/components/editor/_service-editor.scss
  packages/legend-art/style/base/_input.scss
  packages/legend-art/style/components/_selector-input.scss
  packages/legend-extension-dsl-service/src/components/studio/QueryProductionizer.tsx
  packages/legend-extension-dsl-service/src/stores/studio/QueryProductionizerStore.ts
  packages/legend-extension-dsl-service/style/_query-productionizer.scss
  packages/legend-server-sdlc/src/SDLCServerClient.ts
Labels: cla-present

#1809 clean up xt formats part 1
  .changeset/ten-jars-fly.md
  .changeset/ten-jars-train.md
  packages/legend-application-studio/src/components/editor/edit-panel/EditPanel.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/element-generation-editor/ElementGenerationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/element-generation-editor/ElementXTGenerationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/element-generation-editor/FileGenerationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/element-generation-editor/FileSystemViewer.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/external-format-editor/DSL_ExternalFormat_BindingElementEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
  packages/legend-application-studio/src/index.ts
  packages/legend-application-studio/src/stores/DSL_Generation_LegendStudioApplicationPlugin_Extension.ts
  packages/legend-application-studio/src/stores/ExplorerTreeState.ts
  packages/legend-application-studio/src/stores/editor-state/ExternalFormatState.ts
  packages/legend-application-studio/src/stores/editor-state/FileGenerationState.ts
  packages/legend-application-studio/src/stores/editor-state/FileGenerationViewerState.ts
  packages/legend-application-studio/src/stores/editor-state/FileSystemState.ts
  packages/legend-application-studio/src/stores/editor-state/GraphGenerationState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/ElementEditorState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/ElementExternalFormatGenerationState.ts
  packages/legend-application-studio/src/stores/shared/FileSystemTreeUtils.ts
  packages/legend-application-studio/style/components/editor/_external-format-editor.scss
  packages/legend-extension-format-morphir/src/components/FMT_Morphir_LegendStudioApplicationPlugin.tsx
  packages/legend-graph/src/graphManager/AbstractPureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/V1_Engine.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/V1_EngineServerClient.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/externalFormat/V1_GenerateSchemaInput.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_DSL_ExternalFormat_Transformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_DSL_ExternalFormat_ProtocolHelper.ts
Labels: cla-present

#1785 Show dependency project information in explorer panel
  .changeset/smart-swans-fetch.md
  .changeset/twenty-lizards-trade.md
  packages/legend-application-studio/src/components/editor/command-center/ProjectSearchCommand.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/ConnectionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/EnumerationMappingEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/InstanceSetImplementationSourceSelectorModal.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/MappingExecutionQueryBuilder.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/NewMappingElementModal.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/ClassEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/CreateNewElementModal.tsx
  packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
  packages/legend-application-studio/src/stores/DependencyProjectViewerHelper.ts
  packages/legend-application-studio/src/stores/ExplorerTreeState.ts
  packages/legend-application-studio/src/stores/shared/PackageTreeUtils.ts
  packages/legend-application/src/components/shared/PackageableElementOptionLabel.tsx
  packages/legend-extension-dsl-data-space/src/components/query/DataSpaceQueryBuilder.tsx
  packages/legend-graph/src/graph/BasicModel.ts
  packages/legend-graph/src/graph/DependencyManager.ts
  packages/legend-graph/src/graph/helpers/DomainHelper.ts
  packages/legend-graph/src/graphManager/action/changeDetection/GraphObserverHelper.ts
  packages/legend-query-builder/src/components/QueryBuilderConstantExpressionPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderSideBar.tsx
  packages/legend-query-builder/src/components/workflows/ClassQueryBuilder.tsx
  packages/legend-query-builder/src/components/workflows/MappingQueryBuilder.tsx
  packages/legend-query-builder/src/stores/explorer/QueryFunctionsExplorerState.ts
Labels: cla-present

#1810 fix regression introduced in #1693
  .changeset/mean-oranges-invite.md
  packages/legend-application-studio/src/stores/EditorStore.ts
Labels: cla-present

#1752 fix m2m mapping test suite
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar-mismatch/cases/m2m-mapping-test-suites.pure
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/m2m-mapping-test-suites.pure
Labels: cla-present, Status: Waiting for Backend Change

#1813 Add integration test on navigation of dependency tree
  .changeset/fifty-fireants-fetch.md
  packages/legend-application-studio/src/components/editor/side-bar/__tests__/DependencyTree.test.tsx
Labels: cla-present

#1808 service execution tab ui imp: support opening query builder by double-clicking the read-only query in the service execution tab
  .changeset/green-emus-hang.md
  .changeset/wicked-dancers-reflect.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionQueryEditor.tsx
  packages/legend-query-builder/src/index.ts
Labels: cla-present

#1815 fix: groupBy attribute for mappings
  .changeset/contemplative-cardinals-chirp.md
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_RelationalClassMappingBuilderHelper.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/STO_Relational-relational-mapping-groupby.pure
Labels: cla-present, Type: Bug, Studio Core Team, Application: Studio

#1817 renaming test data of mapping test suites
  .changeset/early-parrots-end.md
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/mapping/MappingTestData.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/mapping/MappingTestSuite.ts
  packages/legend-graph/src/graphManager/action/changeDetection/DSL_Mapping_ObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/mapping/V1_MappingTestData.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/mapping/V1_MappingTestSuite.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_MappingBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_MappingSerializationHelper.ts
Labels: cla-present

#1669 query builder fixes
  .changeset/pink-rivers-chew.md
  .changeset/thankful-turkeys-tarry.md
  packages/legend-application-query-bootstrap/style/index.scss
  packages/legend-application-studio/src/stores/editor/NewElementState.ts
  packages/legend-art/style/base/_panel.scss
  packages/legend-manual-tests/cypress/script-docs/conflict-resolution.md
  packages/legend-query-builder/src/components/QueryBuilder.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderResultModifierPanel.tsx
  packages/legend-query-builder/src/components/shared/BasicValueSpecificationEditor.tsx
  packages/legend-query-builder/src/components/shared/LambdaEditor.tsx
  packages/legend-query-builder/style/_query-builder-olap.scss
  packages/legend-query-builder/style/_query-builder-projection.scss
  packages/legend-query-builder/style/_query-builder.scss
  packages/legend-query-builder/style/shared/_lambda-editor.scss
  packages/legend-query-builder/style/shared/_value-spec-editor.scss
  packages/legend-shared/package.json
  packages/legend-shared/src/format/FormatterUtils.ts
  packages/legend-shared/src/format/__tests__/FormatterUtils.test.ts
  yarn.lock
Labels: cla-present, Type: Enhancement, Application: Query

#1798 more cleanup after removing graph building from text mode
  .changeset/six-gifts-switch.md
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/EditorTabManagerState.ts
Labels: cla-present

#1820 bump dependencies
  .changeset/gullible-geese-gesture.md
  fixtures/legend-mock-server/package.json
  package.json
  packages/babel-preset/package.json
  packages/eslint-plugin/package.json
  packages/legend-application-pure-ide-deployment/package.json
  packages/legend-application-pure-ide/package.json
  packages/legend-application-query-bootstrap/package.json
  packages/legend-application-query-deployment/package.json
  packages/legend-application-query/package.json
  packages/legend-application-studio-bootstrap/package.json
  packages/legend-application-studio-deployment/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-taxonomy-bootstrap/package.json
  packages/legend-application-taxonomy-deployment/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-mastery/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-service/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-format-json-schema/package.json
  packages/legend-extension-format-morphir/package.json
  packages/legend-extension-store-flat-data/package.json
  packages/legend-extension-store-relational/package.json
  packages/legend-extension-store-service-store/package.json
  packages/legend-extension-tracer-zipkin/package.json
  packages/legend-graph/package.json
  packages/legend-manual-tests/package.json
  packages/legend-query-builder/package.json
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-storage/package.json
  packages/stylelint-config/package.json
  scripts/typedoc-theme/package.json
  yarn.lock
Labels: cla-present, dependencies

#1811 minor code cleanup fix
  .changeset/ninety-penguins-applaud.md
  packages/legend-application-studio/src/components/editor/edit-panel/element-generation-editor/FileGenerationEditor.tsx
Labels: cla-present

#1805 Automate milestoning github issues
  .github/workflows/bot__onboard-new-issue.yml
  scripts/github-bot/onboardNewIssue.js
Labels: cla-present

#1825 Fix creating default custom runtime for services with nested M2M mapping
  .changeset/afraid-suits-listen.md
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/RuntimeEditorState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceExecutionState.ts
Labels: cla-present

#1827 fix generate test data for relational
  .changeset/wicked-eyes-listen.md
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestDataState.ts
  packages/legend-application-studio/src/stores/shared/testable/TestableUtils.ts
  packages/legend-application-studio/src/stores/shared/testable/__tests__/TestableUtil.test.ts
Labels: cla-present

#1829 Fix regression introduced in #1798
  .changeset/swift-timers-tease.md
  packages/legend-application-studio/src/stores/EditorGraphState.ts
Labels: cla-present

#1831 fix the broken query execution test
  .changeset/mean-mangos-drop.md
  packages/legend-manual-tests/src/__tests__/query-execution/QueryBuilderExecution.test.tsx
Labels: cla-present

#1834 Support semi-interactive registration of services from Standalone query
  .changeset/beige-rocks-wave.md
  .changeset/proud-ears-cry.md
  packages/legend-application-query/src/application/LegendQueryApplicationConfig.ts
  packages/legend-application-studio/src/index.ts
  packages/legend-extension-dsl-service/src/components/query/DSL_Service_LegendQueryApplicationPlugin.tsx
  packages/legend-extension-dsl-service/src/components/studio/ServiceRegisterModal.tsx
  packages/legend-extension-dsl-service/src/stores/studio/QueryProductionizerStore.ts
  packages/legend-extension-dsl-service/style/_service-register-modal.scss
  packages/legend-extension-dsl-service/style/index.scss
Labels: cla-present

#1823 minor changes to dependency explorer tree
  .changeset/fifty-swans-sniff.md
  packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
  packages/legend-application-studio/src/components/editor/side-bar/__tests__/DependencyTree.test.tsx
  packages/legend-application-studio/src/stores/editor/EditorMode.ts
  packages/legend-application-studio/src/stores/editor/StandardEditorMode.ts
  packages/legend-application-studio/src/stores/project-viewer/ProjectViewerEditorMode.ts
  packages/legend-application-studio/src/stores/shared/PackageTreeUtils.ts
Labels: cla-present

#1835 minor improvements in service tests flow
  .changeset/popular-balloons-swim.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestDataEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/testable/ServiceTestableEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceEditorState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestEditorState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestableState.ts
Labels: cla-present

#1842 minor improvements to conflict viewer
  .changeset/fast-mice-give.md
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectDependencyEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/project-configuration-editor-state/ProjectDependencyEditorState.ts
  packages/legend-server-depot/src/ProjectDependencyGraphReportHelper.ts
Labels: cla-present

#1841 update dependencies
  .changeset/slow-cats-begin.md
  fixtures/legend-mock-server/package.json
  package.json
  packages/babel-preset/package.json
  packages/eslint-plugin/package.json
  packages/legend-application-pure-ide-deployment/package.json
  packages/legend-application-pure-ide/package.json
  packages/legend-application-query-bootstrap/package.json
  packages/legend-application-query-deployment/package.json
  packages/legend-application-query/package.json
  packages/legend-application-studio-bootstrap/package.json
  packages/legend-application-studio-deployment/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-taxonomy-bootstrap/package.json
  packages/legend-application-taxonomy-deployment/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-mastery/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-service/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-format-json-schema/package.json
  packages/legend-extension-format-morphir/package.json
  packages/legend-extension-store-flat-data/package.json
  packages/legend-extension-store-relational/package.json
  packages/legend-extension-store-service-store/package.json
  packages/legend-extension-tracer-zipkin/package.json
  packages/legend-graph/package.json
  packages/legend-manual-tests/package.json
  packages/legend-query-builder/package.json
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-storage/package.json
  packages/stylelint-config/package.json
  scripts/typedoc-theme/package.json
  yarn.lock
Labels: cla-present

#1852 Fix a bug with registering service in standalone query
  .changeset/tough-peaches-sit.md
  packages/legend-extension-dsl-service/src/components/query/DSL_Service_LegendQueryApplicationPlugin.tsx
  packages/legend-extension-dsl-service/src/components/query/ServiceRegisterModal.tsx
  packages/legend-extension-dsl-service/src/components/studio/QueryProductionizer.tsx
Labels: cla-present

#1856 Add more options to advanced dropdown in query builder
  .changeset/cameras-nope-yes.md
  .changeset/plenty-cameras-hang.md
  packages/legend-application/src/stores/LegendApplicationDocumentation.ts
  packages/legend-query-builder/src/components/QueryBuilder.tsx
Labels: cla-present

#1857 Fix bug with service registration in standalone query
  .changeset/warm-garlics-allow.md
  packages/legend-extension-dsl-service/src/components/query/DSL_Service_LegendQueryApplicationPlugin.tsx
  packages/legend-extension-dsl-service/src/components/query/ServiceRegisterModal.tsx
  packages/legend-extension-dsl-service/src/stores/studio/QueryProductionizerStore.ts
  packages/legend-query-builder/src/components/QueryBuilder.tsx
Labels: cla-present

#1859 loading indicator for query and css fixes for query
  .changeset/gullible-gulls-goad.md
  .changeset/tyrannical-terns-threaten.md
  packages/legend-art/src/components/LoadingIcon.tsx
  packages/legend-art/src/components/panel/BlankPanelPlaceholder.tsx
  packages/legend-art/src/components/panel/Panel.tsx
  packages/legend-art/src/index.ts
  packages/legend-art/style/components/_icon.scss
  packages/legend-query-builder/src/components/QueryBuilderConstantExpressionPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderTextEditor.tsx
  packages/legend-query-builder/src/stores/QueryBuilderTextEditorState.ts
  packages/legend-query-builder/style/shared/_value-spec-editor.scss
Labels: cla-present, Application: Query, Component: UX/Design

#1858 update dependencies
  .changeset/lucky-houses-drive.md
  package.json
  packages/legend-application-pure-ide/package.json
  packages/legend-application-query/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-mastery/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-service/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-format-json-schema/package.json
  packages/legend-extension-format-morphir/package.json
  packages/legend-extension-store-flat-data/package.json
  packages/legend-extension-store-relational/package.json
  packages/legend-extension-store-service-store/package.json
  packages/legend-extension-tracer-zipkin/package.json
  packages/legend-graph/package.json
  packages/legend-manual-tests/package.json
  packages/legend-query-builder/package.json
  packages/legend-server-depot/package.json
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-storage/package.json
  yarn.lock
Labels: cla-present

#1863 handle sort on all TDS columns and fix result modifiers on OLAP queries
  .changeset/cuddly-insects-dress.md
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderResultModifierPanel.tsx
  packages/legend-query-builder/src/stores/__tests__/QueryBuilderBuildLambdaRoundtrip.test.tsx
  packages/legend-query-builder/src/stores/__tests__/QueryBuilderProcessingRoundtrip.test.ts
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder__OLAPGroupBy.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/QueryResultSetModifierState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/projection/QueryBuilderProjectionStateBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/projection/QueryBuilderProjectionValueSpecificationBuilder.ts
Labels: cla-present
