Repository finos/legend-studio, pull requests merged in 2023-02, with the labels that each got.

#1845 Handle testable refactor
  .changeset/early-boats-confess.md
  .changeset/long-parents-cover.md
  .changeset/moody-tips-give.md
  packages/legend-application-studio/src/components/editor/side-bar/testable/GlobalTestRunner.tsx
  packages/legend-application-studio/src/index.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/testable/ServiceTestableState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/testable/TestAssertionState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/testable/TestableEditorState.ts
  packages/legend-application-studio/src/stores/sidebar-state/testable/GlobalTestRunnerState.ts
  packages/legend-extension-dsl-persistence/src/graph/metamodel/pure/model/packageableElements/persistence/DSL_Persistence_PersistenceTestBatch.ts
  packages/legend-extension-dsl-persistence/src/graphManager/action/changeDetection/DSL_Persistence_ObserverHelper.ts
  packages/legend-extension-dsl-persistence/src/graphManager/protocol/pure/v1/model/packageableElements/persistence/V1_DSL_Persistence_PersistenceTestBatch.ts
  packages/legend-extension-dsl-persistence/src/graphManager/protocol/pure/v1/transformation/pureProtocol/V1_DSL_Persistence_ProtocolHelper.ts
  packages/legend-graph/src/graph/metamodel/pure/test/result/AtomicTestId.ts
  packages/legend-graph/src/graph/metamodel/pure/test/result/RunTestsTestableInput.ts
  packages/legend-graph/src/graph/metamodel/pure/test/result/TestResult.ts
  packages/legend-graph/src/graph/metamodel/pure/test/result/UniqueTestId.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/test/V1_RunTestsInput.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/test/V1_TestBatch.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/test/V1_UniqueTestId.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/test/result/V1_TestResult.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_TestResultBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_TestSerializationHelper.ts
  packages/legend-graph/src/index.ts
Labels: cla-present

#1865 fix rendering of service editor in archive mode
  .changeset/healthy-apple-warrior.md
  .changeset/healthy-apricots-work.md
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceEditorState.ts
  packages/legend-server-sdlc/src/SDLCServerClient.ts
Labels: cla-present

#1836 Add default config files to Studio, Query Docker images
  .changeset/eleven-cameras-kick.md
  .prettierignore
  packages/legend-application-query-deployment/Dockerfile
  packages/legend-application-query-deployment/config/httpConfig.json
  packages/legend-application-query-deployment/config/uiConfig.json
  packages/legend-application-query-deployment/entrypoint.sh
  packages/legend-application-studio-deployment/Dockerfile
  packages/legend-application-studio-deployment/config/httpConfig.json
  packages/legend-application-studio-deployment/config/uiConfig.json
  packages/legend-application-studio-deployment/entrypoint.sh
Labels: cla-present

#1873 pretty display execution time in query results
  .changeset/spitty-bees-make.md
  .changeset/spotty-bees-tease.md
  packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
  packages/legend-query-builder/src/stores/QueryBuilderResultState.ts
  packages/legend-shared/src/__tests__/DateUtil.test.ts
  packages/legend-shared/src/date/DateUtils.ts
Labels: cla-present

#1879 Minor fixes
  .changeset/cool-pianos-exercise.md
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionQueryEditor.tsx
  packages/legend-application-taxonomy/src/components/TaxonomyNodeViewer.tsx
  packages/legend-extension-dsl-service/src/components/query/ServiceRegisterModal.tsx
Labels: cla-present

#1833 Apply strict rules for association properties
  .changeset/breezy-mangos-raise.md
  .changeset/quick-books-switch.md
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/AssociationEditor.tsx
  packages/legend-application-studio/style/components/editor/uml-editor/_class-editor.scss
  packages/legend-application/src/stores/LegendApplicationDocumentation.ts
  packages/legend-graph/src/graphManager/GraphManagerState.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_DomainBuilderHelper.ts
Labels: cla-present

#1886 add test for strict association property check
  .changeset/plenty-drinks-mix.md
  packages/legend-graph/src/graphManager/__tests__/buildGraph/GraphBuildFailure.test.ts
  packages/legend-graph/src/graphManager/__tests__/buildGraph/TEST_DATA__GraphBuildFailure.ts
Labels: cla-present

#1883 Don't fetch mapping analysis if mapping hasn't changed
  .changeset/swift-rivers-kick.md
  packages/legend-application-query/src/components/QueryEditorComponentTestUtils.tsx
  packages/legend-graph/src/graphManager/AbstractPureGraphManager.ts
  packages/legend-graph/src/graphManager/action/analytics/MappingModelCoverageAnalysis.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/V1_EngineServerClient.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/analytics/V1_MappingModelCoverageAnalysis.ts
  packages/legend-query-builder/src/components/QueryBuilderComponentTestUtils.tsx
  packages/legend-query-builder/src/components/explorer/QueryBuilderExplorerPanel.tsx
  packages/legend-query-builder/src/stores/QueryBuilderState.ts
  packages/legend-query-builder/src/stores/QueryBuilderStateTestUtils.ts
  packages/legend-query-builder/src/stores/__tests__/QueryBuilderExplorerTreeNodeMappingAnalysis.test.ts
  packages/legend-query-builder/src/stores/explorer/QueryBuilderExplorerState.ts
Labels: cla-present

#1882 Query styling fixes
  .changeset/elated-eagles-elevate.md
  .changeset/rascallion-robins-riddle.md
  .changeset/tame-wasps-live.md
  packages/legend-application-query-bootstrap/style/index.scss
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectDependencyEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/service/ServiceExecutionState.ts
  packages/legend-application/src/components/execution-plan-viewer/ExecutionPlanViewer.tsx
  packages/legend-art/src/components/dialog/Modal.tsx
  packages/legend-art/src/components/panel/Panel.tsx
  packages/legend-art/style/base/_modal.scss
  packages/legend-art/style/base/_panel.scss
  packages/legend-art/style/components/_icon.scss
  packages/legend-manual-tests/src/__tests__/query-execution/QueryBuilderExecution.test.tsx
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderTextEditor.tsx
  packages/legend-query-builder/src/components/shared/LambdaParameterValuesEditor.tsx
  packages/legend-query-builder/src/components/shared/QueryBuilderVariableSelector.tsx
  packages/legend-query-builder/src/stores/QueryBuilderResultState.ts
  packages/legend-query-builder/src/stores/shared/LambdaParameterState.ts
  packages/legend-query-builder/style/shared/_value-spec-editor.scss
Labels: cla-present, Application: Query, Component: UX/Design

#1892 minor fixes to pure ide
  .changeset/tasty-wasps-compete.md
  packages/legend-application-pure-ide-deployment/scripts/setup.js
  packages/legend-application/src/stores/PureLanguageSupport.ts
Labels: cla-present

#1885 Fix showing preview data for milestoned properties
  .changeset/eighty-lizards-cover.md
  packages/legend-query-builder/src/components/explorer/QueryBuilderExplorerPanel.tsx
  packages/legend-query-builder/src/graphManager/QueryBuilderSupportedFunctions.ts
  packages/legend-query-builder/src/stores/QueryBuilderPreviewDataHelper.ts
  packages/legend-query-builder/src/stores/QueryBuilderResultState.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts
  packages/legend-query-builder/src/stores/__tests__/QueryBuilderPreviewData.test.ts
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder_PreviewDataTest.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/projection/QueryBuilderProjectionValueSpecificationBuilder.ts
  packages/legend-query-builder/style/_query-builder-explorer.scss
Labels: cla-present

#1847 Fix a bug where packageableElement in the explorer tree can't be renamed
  .changeset/shy-years-turn.md
  packages/legend-application-studio/src/components/__tests__/LegendStudioExplorerTree.test.tsx
  packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
  packages/legend-application-studio/src/stores/ExplorerTreeState.ts
  packages/legend-application-studio/style/components/editor/side-bar/_explorer.scss
Labels: cla-present

#1893 minor cleanups
  .changeset/calm-grapes-shop.md
  packages/legend-query-builder/src/stores/QueryBuilderPreviewDataHelper.ts
  packages/legend-query-builder/src/stores/QueryBuilderResultState.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts
Labels: cla-present

#1876 Add project dependants tab for project config
  .changeset/empty-waves-jog.md
  .changeset/sanguine-sparrows-seek.md
  packages/legend-application-studio/src/components/editor/side-bar/ProjectDependantsEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/ProjectOverview.tsx
  packages/legend-application-studio/src/stores/LegendStudioRouter.ts
  packages/legend-application-studio/src/stores/sidebar-state/ProjectDependantEditorState.ts
  packages/legend-application-studio/src/stores/sidebar-state/ProjectOverviewState.ts
  packages/legend-application-studio/style/components/editor/side-bar/_project-overview.scss
  packages/legend-art/src/components/Badge.tsx
  packages/legend-art/style/base/_panel.scss
  packages/legend-server-depot/src/DepotServerClient.ts
  packages/legend-server-depot/src/index.ts
  packages/legend-server-depot/src/models/ProjectVersionPlatformDependency.ts
Labels: cla-present, Type: Feature Request, Application: Studio

#1900 minor fix to preview data for milestone properties
  .changeset/rotten-pillows-sit.md
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/QueryBuilderValueSpecificationBuilderHelper.ts
Labels: cla-present

#1899 fix: toogle text mode shortcut in view/archive mode
  .changeset/new-vans-develop.md
  packages/legend-application-studio/src/stores/EditorStore.ts
Labels: cla-present

#1896 Minor improvements for checking entitlements
  .changeset/cuddly-flowers-smash.md
  packages/legend-query-builder/src/components/QueryBuilder.tsx
Labels: cla-present

#1907 rename olap to window functions
  .changeset/gentle-buttons-walk.md
  packages/legend-query-builder/src/components/QueryBuilder.tsx
  packages/legend-query-builder/src/components/QueryBuilder_TestID.ts
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderPostFilterPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderPostTDSPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderTDSWindowPanel.tsx
  packages/legend-query-builder/src/graphManager/QueryBuilderHashUtils.ts
  packages/legend-query-builder/src/stores/QueryBuilderStateBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/QueryBuilderTDSState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/olapGroupBy/QueryBuilderOLAPGroupByOperatorLoader.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/operators/QueryBuilderPostFilterOperatorHelper.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/projection/QueryBuilderProjectionValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/QueryBuilderWindowGroupByOperatorLoader.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/QueryBuilderWindowState.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/QueryBuilderWindowStateBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/QueryBuilderWindowValueSpecificationBuilder.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/operators/QueryBuilderTDS_WindowOperator.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/operators/QueryBuilderTDS_WindowOperator_Average.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/operators/QueryBuilderTDS_WindowOperator_Count.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/operators/QueryBuilderTDS_WindowOperator_Max.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/operators/QueryBuilderTDS_WindowOperator_Min.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/operators/QueryBuilderTDS_WindowOperator_Sum.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/operators/QueryBuilderTDS_WindowRankOperator_AverageRank.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/operators/QueryBuilderTDS_WindowRankOperator_DenseRank.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/operators/QueryBuilderTDS_WindowRankOperator_Rank.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/window/operators/QueryBuilderTDS_WindowRankOperator_RowNumber.ts
Labels: cla-present

#1887 add dispose method for association to clean properties added through it
  .changeset/seven-roses-jog.md
  packages/legend-application-studio/src/stores/__tests__/ProjectDependencyManager.test.ts
  packages/legend-application-studio/src/stores/__tests__/TEST_DATA__ProjectDependencyManager.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/domain/Association.ts
Labels: cla-present

#1849 Fix: fix a bug related to navigation to function in text mode
  .changeset/flat-kids-pretend.md
  packages/legend-application-studio/src/stores/__tests__/GrammarTestEditor.test.ts
  packages/legend-application-studio/src/stores/editor-state/GrammarTextEditorState.ts
Labels: cla-present

#1910 update github commands
  .github/workflows/bot__new-issue-track.yml
  .github/workflows/bot__onboard-new-issue.yml
  .github/workflows/check-build.yml
  .github/workflows/check-changeset.yml
  .github/workflows/check-code.yml
  .github/workflows/check-docker.yml
  .github/workflows/check-security-and-quality.yml
  .github/workflows/manual__prepare-new-release.yml
  .github/workflows/manual__publish-docker.yml
  .github/workflows/manual__publish-npm-snapshot.yml
  .github/workflows/publish-docker-snapshot.yml
  .github/workflows/publish-website.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  3
  packages/legend-manual-tests/src/__tests__/query-execution/TEMPORARY__QueryBuilderExecution.test.tsx
Labels: cla-present

#1913 pure ide: minor fix
  .changeset/soft-laws-share.md
  packages/legend-application-pure-ide/package.json
  packages/legend-application-pure-ide/src/components/editor/side-bar/DirectoryTreeExplorer.tsx
  packages/legend-application-pure-ide/src/server/models/DirectoryTree.ts
  packages/legend-application-query/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-query-builder/package.json
  yarn.lock
Labels: cla-present

#1909 Only add properties with unique name and path in query builder
  .changeset/happy-hummingbirds-hop.md
  .changeset/neat-papayas-double.md
  .changeset/treacherous-terns-tell.md
  packages/legend-application-studio/src/components/editor/StatusBar.tsx
  packages/legend-art/src/components/CJS__Icon.cts
  packages/legend-query-builder/src/components/__tests__/QueryBuilderFetchStructure.test.tsx
  packages/legend-query-builder/src/components/explorer/QueryBuilderExplorerPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderPostFilterPanel.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderTDSPanel.tsx
  packages/legend-query-builder/src/components/filter/QueryBuilderFilterPanel.tsx
  packages/legend-shared/src/format/FormatterUtils.ts
  packages/legend-shared/src/format/__tests__/FormatterUtils.test.ts
Labels: cla-present, Type: Enhancement, Application: Query, Component: UX/Design

#1911 Clarify status of sorting column in query builder
  .changeset/little-kangaroos-crash.md
  packages/legend-application-query-bootstrap/style/index.scss
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderResultModifierPanel.tsx
  packages/legend-query-builder/style/_query-builder-projection.scss
Labels: cla-present, Application: Query, Component: UX/Design

#1920 fix duplicate call of transform
  .changeset/yellow-flowers-drum.md
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_Core_SystemModels.json
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
Labels: cla-present

#1912 Add fetch versions of a project for depot
  .changeset/big-trees-flow.md
  .changeset/bleak-bats-battle.md
  packages/legend-application-query/src/components/QueryEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectDependencyEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/testable/TestAssertionEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/WorkflowManager.tsx
  packages/legend-application-studio/src/components/editor/side-bar/testable/GlobalTestRunner.tsx
  packages/legend-art/src/components/Button.tsx
  packages/legend-art/src/index.ts
  packages/legend-art/style/base/_panel.scss
  packages/legend-query-builder/src/components/QueryBuilder.tsx
  packages/legend-query-builder/src/components/QueryBuilderConstantExpressionPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderDiffPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderPropertyExpressionEditor.tsx
  packages/legend-query-builder/src/components/explorer/QueryBuilderExplorerPanel.tsx
  packages/legend-query-builder/src/components/explorer/QueryBuilderMilestoningEditor.tsx
  packages/legend-query-builder/src/components/fetch-structure/QueryBuilderTDSWindowPanel.tsx
  packages/legend-query-builder/src/components/watermark/QueryBuilderWatermark.tsx
  packages/legend-server-depot/src/DepotServerClient.ts
Labels: cla-present, Application: Studio, Component: UX/Design

#1924 Expose TDS types in type selectors
  .changeset/tall-tips-explode.md
  packages/legend-graph/src/graph/MetaModelConst.ts
  packages/legend-graph/src/graph/helpers/PureLanguageHelper.ts
  packages/legend-graph/src/graphManager/Core_PureGraphManagerPlugin.ts
Labels: cla-present

#1916 Query builder fixes
  .changeset/fluffy-bottles-sort.md
  .changeset/modern-worms-relax.md
  packages/legend-application-query/src/stores/QueryEditorStore.ts
  packages/legend-query-builder/src/components/QueryBuilder.tsx
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderPropertyExpressionEditor.tsx
  packages/legend-query-builder/src/components/shared/CustomDatePicker.tsx
  packages/legend-query-builder/src/components/shared/QueryBuilderVariableSelector.tsx
  packages/legend-query-builder/src/stores/QueryBuilderState.ts
  packages/legend-query-builder/style/_query-builder.scss
Labels: cla-present, Component: Query Builder, Application: Query, Component: UX/Design

#1926 fix execute mapping class css
  .changeset/green-ducks-pump.md
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/MappingExecutionBuilder.tsx
Labels: cla-present

#1930 use Github Actions to publish pages
  .github/workflows/publish-website.yml
Labels: cla-present

#1931 minor fix
  .github/workflows/publish-website.yml
Labels: cla-present

#1932 minor fix
  .github/workflows/publish-website.yml
Labels: cla-present

#1933 only allow publish website to run in main repo
  .github/workflows/publish-website.yml
Labels: cla-present

#1935 Use strategic test suite for service code snippets
  .changeset/real-houses-beam.md
  packages/legend-application-studio/src/stores/LegendStudioCodeSnippets.ts
Labels: cla-present

#1934 Add tests for expected query builder behavior
  .changeset/green-onions-yell.md
  packages/legend-query-builder/src/components/QueryBuilderConstantExpressionPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderParametersPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilder_TestID.ts
  packages/legend-query-builder/src/components/__tests__/QueryBuilderFetchStructure.test.tsx
  packages/legend-query-builder/src/components/__tests__/QueryBuilderVariables.test.tsx
  packages/legend-query-builder/src/components/__tests__/TEST_DATA_QueryBuilder_Query_Execution.ts
  packages/legend-query-builder/src/components/shared/CustomDatePicker.tsx
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder_Generic.ts
Labels: cla-present, Studio Core Team, Component: Query Builder, Application: Query

#1942 Fixes re-rendering of query builder results data table
  .changeset/pistachio-pigeons-ponder.md
  packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
Labels: cla-present, Type: Bug, Application: Query

#1914 minor check entitlements code improvement
  .changeset/khaki-suits-remember.md
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-graph/src/index.ts
  packages/legend-query-builder/src/components/QueryBuilder.tsx
Labels: cla-present

#1939 Improve readability of Query Builder buttons
  .changeset/blustering-birds-blunder.md
  .changeset/delirious-doves-dance.md
  .changeset/grumpy-pets-reflect.md
  packages/legend-application-query-bootstrap/style/index.scss
  packages/legend-application-query/src/components/Core_LegendQueryApplicationPlugin.tsx
  packages/legend-application-query/src/components/QueryEditor.tsx
  packages/legend-application-query/style/_query-editor.scss
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectDependencyEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/ProjectDependantsEditor.tsx
  packages/legend-application-studio/src/stores/sidebar-state/ProjectOverviewState.ts
  packages/legend-application-studio/style/components/editor/_project-configuration-editor.scss
  packages/legend-art/src/components/CJS__Icon.cts
  packages/legend-art/src/components/menu/MenuContent.tsx
  packages/legend-art/style/base/_button.scss
  packages/legend-extension-dsl-data-space/src/components/DataSpaceViewer.tsx
  packages/legend-extension-dsl-data-space/style/_data-space-viewer.scss
  packages/legend-extension-dsl-service/src/components/query/DSL_Service_LegendQueryApplicationPlugin.tsx
  packages/legend-extension-dsl-service/src/components/query/ServiceRegisterModal.tsx
  packages/legend-server-depot/src/DepotServerClient.ts
Labels: cla-present, Studio Core Team, Component: Query Builder, Application: Query, Component: UX/Design

#1945 metrics: report when database-builder is accessed
  .changeset/little-files-sit.md
  packages/legend-application-studio/src/components/Core_LegendStudioApplicationPlugin.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/DatabaseBuilder.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/data-editor/RelationalCSVDataEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/external-format-editor/DSL_ExternalFormat_BindingElementEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/ClassMappingEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectConfigurationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/CreateNewElementModal.tsx
  packages/legend-application-studio/src/components/editor/side-bar/WorkflowManager.tsx
  packages/legend-application-studio/src/components/editor/side-bar/WorkspaceReview.tsx
  packages/legend-application-studio/src/stores/LegendStudioApplicationNavigationContext.ts
Labels: cla-present

#1946 Add option to edit text of H2 database table in expanded modal
  .changeset/neat-cooks-work.md
  .changeset/superb-starlings-serrate.md
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/RelationalDatabaseConnectionEditor.tsx
  packages/legend-art/style/base/_button.scss
Labels: cla-present, Application: Studio, Component: UX/Design

#1951 minor cleanups
  .changeset/early-coats-happen.md
  3
  CODEOWNERS
  fixtures/legend-mock-server/package.json
  package.json
  packages/babel-preset/package.json
  packages/legend-application-pure-ide-deployment/package.json
  packages/legend-application-pure-ide/package.json
  packages/legend-application-query-bootstrap/package.json
  packages/legend-application-query-deployment/package.json
  packages/legend-application-query/package.json
  packages/legend-application-query/src/stores/CreateMappingQuerySetupStore.ts
  packages/legend-application-query/src/stores/QueryEditorStore.ts
  packages/legend-application-studio-bootstrap/package.json
  packages/legend-application-studio-deployment/package.json
  packages/legend-application-studio/package.json
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/project-viewer/ProjectViewerStore.ts
  packages/legend-application-taxonomy-bootstrap/package.json
  packages/legend-application-taxonomy-deployment/package.json
  packages/legend-application-taxonomy/package.json
  packages/legend-application/package.json
  packages/legend-art/package.json
  packages/legend-dev-utils/package.json
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-diagram/package.json
  packages/legend-extension-dsl-mastery/package.json
  packages/legend-extension-dsl-persistence-cloud/package.json
  packages/legend-extension-dsl-persistence/package.json
  packages/legend-extension-dsl-service/package.json
  packages/legend-extension-dsl-text/package.json
  packages/legend-extension-format-json-schema/package.json
  packages/legend-extension-format-morphir/package.json
  packages/legend-extension-store-flat-data/package.json
  packages/legend-extension-store-relational/package.json
  packages/legend-extension-store-service-store/package.json
  packages/legend-extension-tracer-zipkin/package.json
  packages/legend-graph/package.json
  packages/legend-graph/src/graph/DependencyManager.ts
  packages/legend-graph/src/graphManager/AbstractPureGraphManager.ts
  packages/legend-graph/src/graphManager/__tests__/buildGraph/Dependency.test.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
  packages/legend-manual-tests/package.json
  packages/legend-query-builder/package.json
  packages/legend-query-builder/src/graphManager/protocol/pure/QueryBuilder_PureGraphManagerExtension.ts
  packages/legend-query-builder/src/graphManager/protocol/pure/v1/V1_QueryBuilder_PureGraphManagerExtension.ts
  packages/legend-server-depot/package.json
  packages/legend-server-depot/src/DepotServerClient.ts
  packages/legend-server-sdlc/package.json
  packages/legend-shared/package.json
  packages/legend-storage/package.json
  packages/stylelint-config/package.json
  scripts/typedoc-theme/package.json
  yarn.lock
Labels: cla-present

#1938 Introduce module legend-extension-format-graphql
  .changeset/wise-bugs-float.md
  packages/legend-application-query-bootstrap/package.json
  packages/legend-application-query-bootstrap/src/index.tsx
  packages/legend-application-query-bootstrap/tsconfig.build.json
  packages/legend-application-query-bootstrap/tsconfig.json
  packages/legend-application-studio-bootstrap/package.json
  packages/legend-application-studio-bootstrap/src/index.tsx
  packages/legend-application-studio-bootstrap/tsconfig.build.json
  packages/legend-application-studio-bootstrap/tsconfig.json
  packages/legend-extension-format-graphql/.npmignore
  packages/legend-extension-format-graphql/README.md
  packages/legend-extension-format-graphql/_package.config.js
  packages/legend-extension-format-graphql/jest.config.js
  packages/legend-extension-format-graphql/package.json
  packages/legend-extension-format-graphql/src/FMT_GraphQL_Extension.ts
  packages/legend-extension-format-graphql/src/graphManager/FMT_GraphQL_PureGraphManagerPlugin.ts
  packages/legend-extension-format-graphql/src/graphManager/protocol/pure/FMT_GraphQL_PureProtocolProcessorPlugin.ts
  packages/legend-extension-format-graphql/src/graphManager/protocol/pure/v1/V1_FMT_GraphQL_SystemModels.json
  packages/legend-extension-format-graphql/src/index.ts
  packages/legend-extension-format-graphql/tsconfig.build.json
  packages/legend-extension-format-graphql/tsconfig.json
  packages/legend-extension-format-graphql/tsconfig.package.json
  packages/legend-extension-format-graphql/tsconfig.publish.json
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: cla-present

#1955 Styling button fix
  .changeset/weeping-wren-wrestles.md
  packages/legend-extension-dsl-data-space/style/_data-space-viewer.scss
Labels: cla-present

#1953 Fix a bug in which the generation of assertion data produces a misleading error message
  .changeset/little-sheep-itch.md
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
Labels: cla-present, Type: Bug

#1956 fix broken tests and minor Check Entitlement improvements
  .changeset/twelve-geese-tan.md
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/DSL_Mastery-basic.pure
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/DSL_Persistence-basic.pure
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/DSL_Service-basic.pure
  packages/legend-query-builder/src/components/QueryBuilder.tsx
Labels: cla-present

#1959 provide clientVersion for compile/lambdaReturntype api
  .changeset/real-pumpkins-rest.md
  packages/legend-graph/src/graphManager/protocol/pure/v1/V1_PureGraphManager.ts
Labels: cla-present
