Repository finos/legend-studio, pull requests merged in 2023-03, with the labels that each got.

#1961 fix execution duration display
  .changeset/silly-kids-applaud.md
  packages/legend-query-builder/src/stores/QueryBuilderResultState.ts
Labels: cla-present

#1960 Fix pretty const name
  .changeset/cold-rivers-rescue.md
  packages/legend-shared/src/format/FormatterUtils.ts
  packages/legend-shared/src/format/__tests__/FormatterUtils.test.ts
Labels: cla-present, Component: UX/Design, Component: Testing

#1927 support check entitlements in dataspace
  .changeset/lazy-vans-hang.md
  .changeset/twelve-dots-suffer.md
  packages/legend-application-query-bootstrap/src/index.tsx
  packages/legend-application-taxonomy-bootstrap/src/index.tsx
  packages/legend-extension-dsl-data-space/package.json
  packages/legend-extension-dsl-data-space/src/components/DSL_DataSpace_LegendApplicationPlugin.ts
  packages/legend-extension-dsl-data-space/src/components/DataSpaceViewer.tsx
  packages/legend-extension-dsl-data-space/src/index.ts
Labels: cla-present

#1963 Fix calling compile api twice for compilation
  .changeset/olive-doors-cover.md
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/V1_Engine.ts
Labels: cla-present

#1965 Update test for prettyCONSTName
  .changeset/purple-olives-remember.md
  packages/legend-shared/src/format/__tests__/FormatterUtils.test.ts
Labels: cla-present, Component: Testing

#1971 Revert dataspace button
  .changeset/giant-apples-sip.md
  packages/legend-extension-dsl-data-space/src/components/DataSpaceViewer.tsx
  packages/legend-extension-dsl-data-space/style/_data-space-viewer.scss
Labels: cla-present

#1970 Fix dispatch logic for key bindings so that it executes for the correct command key
  .changeset/gorgeous-pans-type.md
  .changeset/poor-glasses-count.md
  packages/legend-application/src/components/LegendApplicationComponentFrameworkProvider.tsx
  packages/legend-application/src/stores/KeyboardShortcutsService.ts
  packages/legend-shared/src/keyboard/KeyBinding.ts
Labels: cla-present

#1967 dataspace check entitlements
  .changeset/grumpy-lobsters-pump.md
  packages/legend-application-taxonomy/src/stores/StandaloneDataSpaceViewerStore.ts
  packages/legend-application-taxonomy/src/stores/TaxonomyNodeViewerState.ts
  packages/legend-extension-dsl-data-space/src/index.ts
  packages/legend-extension-dsl-data-space/src/stores/DataSpaceViewerState.ts
  packages/legend-extension-dsl-data-space/src/stores/query/DataSpaceAdvancedSearchState.ts
Labels: cla-present

#1972 export V1_LegendSDLC, V1_Protocol, and V1_PureModelContextPointer
  .changeset/dull-jars-draw.md
  packages/legend-graph/src/index.ts
Labels: cla-present

#1974 default parameter dates to now/today
  .changeset/quick-pumas-type.md
  packages/legend-query-builder/src/components/__tests__/QueryBuilderVariables.test.tsx
  packages/legend-query-builder/src/components/shared/CustomDatePicker.tsx
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder_Generic.ts
  packages/legend-query-builder/src/stores/shared/ValueSpecificationEditorHelper.ts
Labels: cla-present

#1950 add tab plugin extension for test runner tab
  .changeset/brave-ducks-move.md
  .changeset/frail-flamingos-fall.md
  docs/workflow/local-development-assemblage.md
  packages/legend-application-studio/src/components/LegendStudioTestID.ts
  packages/legend-application-studio/src/components/editor/ActivityBar.tsx
  packages/legend-application-studio/src/components/editor/side-bar/testable/GlobalTestRunner.tsx
  packages/legend-application-studio/src/stores/EditorConfig.ts
  packages/legend-application-studio/src/stores/STO_ProjectOverview_LegendStudioApplicationPlugin_Extension.ts
  packages/legend-art/src/components/panel/Panel.tsx
  packages/legend-art/style/base/_panel.scss
Labels: cla-present, Application: Studio, Component: Testing

#1313 Spanner connector
  .changeset/six-coins-matter.md
  .changeset/smart-bugs-knock.md
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/RelationalDatabaseConnectionEditor.tsx
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/connection/ConnectionEditorState.ts
  packages/legend-application-studio/src/stores/shared/modifier/STO_Relational_GraphModifierHelper.ts
  packages/legend-graph/src/graph/Core_HashUtils.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/relational/connection/DatasourceSpecification.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/relational/connection/RelationalDatabaseConnection.ts
  packages/legend-graph/src/graphManager/action/changeDetection/STO_Relational_ObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/relational/connection/V1_DatasourceSpecification.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/relational/connection/V1_RelationalDatabaseConnection.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_ConnectionTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_RelationalConnectionBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_ConnectionSerializationHelper.ts
Labels: cla-present, Status: Waiting for Backend Change

#1874 Add support for Client side storage to save user preferences
  .changeset/hip-lizards-invite.md
  .changeset/old-rules-buy.md
  .changeset/weak-roses-glow.md
  packages/legend-application-query/src/application/LegendQuery.tsx
  packages/legend-application-studio/src/components/editor/aux-panel/DevTool.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/GrammarTextEditor.tsx
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/LegendStudioStorage.ts
  packages/legend-application-studio/src/stores/editor-state/GrammarTextEditorState.ts
  packages/legend-application/src/index.ts
  packages/legend-application/src/stores/ApplicationStore.ts
  packages/legend-application/src/stores/storage/ApplicationStorage.ts
  packages/legend-application/src/stores/storage/StorageService.ts
  packages/legend-shared/src/error/AssertionUtils.ts
Labels: cla-present

#1985 renaming mapping test data
  .changeset/red-spiders-tickle.md
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/mapping/MappingStoreTestData.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/mapping/MappingTestSuite.ts
  packages/legend-graph/src/graphManager/__tests__/roundtripTestData/TEST_DATA__MappingRoundtrip.ts
  packages/legend-graph/src/graphManager/action/changeDetection/DSL_Mapping_ObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/mapping/V1_MappingStoreTestData.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/mapping/V1_MappingTestSuite.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_MappingTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_MappingBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_MappingSerializationHelper.ts
Labels: cla-present, Status: Waiting for Backend Change

#1990 Restore source information of errors in query builder text editor
  .changeset/chipper-chickens-cluck.md
  .changeset/tough-humans-breathe.md
  packages/legend-art/src/components/dialog/Modal.tsx
  packages/legend-query-builder/src/components/QueryBuilderTextEditor.tsx
  packages/legend-query-builder/src/stores/QueryBuilderTextEditorState.ts
Labels: Type: Regression, Component: Query Builder, Application: Query

#1997 Persist user preferences for editorTheme and showPostFilterPanel
  .changeset/funny-tables-teach.md
  .changeset/two-timers-roll.md
  packages/legend-application-query/src/components/QueryEditor.tsx
  packages/legend-application/src/index.ts
  packages/legend-application/src/stores/ApplicationStore.ts
  packages/legend-application/src/stores/LayoutService.ts
  packages/legend-application/src/stores/storage/ApplicationStorage.ts
  packages/legend-query-builder/src/components/QueryBuilder.tsx
  packages/legend-query-builder/src/stores/LegendQueryStorage.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/QueryBuilderTDSState.ts
Labels: Application: Query

#1898 Refactor code in `EditorStore` to separate out logic for FormMode and TextMode
  .changeset/poor-bobcats-beam.md
  .changeset/violet-icons-lick.md
  packages/legend-application-studio/src/components/__tests__/ClassQueryBuilder.test.tsx
  packages/legend-application-studio/src/components/__tests__/EmbeddedQueryBuilder.test.tsx
  packages/legend-application-studio/src/components/__tests__/LegendStudioExplorerTree.test.tsx
  packages/legend-application-studio/src/components/editor/Editor.tsx
  packages/legend-application-studio/src/components/editor/StatusBar.tsx
  packages/legend-application-studio/src/components/editor/aux-panel/Problems.tsx
  packages/legend-application-studio/src/components/editor/command-center/ProjectSearchCommand.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/FileGenerationViewer.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/FunctionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/GenerationSpecificationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/GrammarTextEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/RuntimeEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/data-editor/EmbeddedDataEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/diff-editor/EntityDiffView.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/MappingExplorer.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/OperationSetImplementationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/mapping-editor/PropertyMappingsEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/service-editor/ServiceExecutionEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/AssociationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/ClassEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/ClassQueryBuilder.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/EnumerationEditor.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/StereotypeSelector.tsx
  packages/legend-application-studio/src/components/editor/edit-panel/uml-editor/TaggedValueEditor.tsx
  packages/legend-application-studio/src/components/editor/side-bar/Explorer.tsx
  packages/legend-application-studio/src/components/editor/side-bar/LocalChanges.tsx
  packages/legend-application-studio/src/components/project-viewer/ProjectViewer.tsx
  packages/legend-application-studio/src/stores/EditorGraphState.ts
  packages/legend-application-studio/src/stores/EditorStore.ts
  packages/legend-application-studio/src/stores/EditorTabManagerState.ts
  packages/legend-application-studio/src/stores/EmbeddedQueryBuilderState.ts
  packages/legend-application-studio/src/stores/ExplorerTreeState.ts
  packages/legend-application-studio/src/stores/GraphEditFormModeState.ts
  packages/legend-application-studio/src/stores/GraphEditGrammarModeState.ts
  packages/legend-application-studio/src/stores/GraphEditorMode.ts
  packages/legend-application-studio/src/stores/__tests__/GrammarTestEditor.test.ts
  packages/legend-application-studio/src/stores/editor-state/GraphGenerationState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/ElementFileGenerationState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/connection/DatabaseBuilderState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/mapping/MappingEditorState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/mapping/MappingExecutionState.ts
  packages/legend-application-studio/src/stores/editor-state/element-editor-state/mapping/MappingTestState.ts
  packages/legend-application-studio/src/stores/editor/NewElementState.ts
  packages/legend-application-studio/src/stores/project-viewer/ProjectViewerStore.ts
  packages/legend-application-studio/src/stores/sidebar-state/LocalChangesState.ts
  packages/legend-application-studio/src/stores/sidebar-state/WorkspaceSyncState.ts
  packages/legend-application-studio/src/stores/sidebar-state/WorkspaceUpdateConflictResolutionState.ts
  packages/legend-extension-dsl-diagram/src/components/studio/DiagramEditor.tsx
  packages/legend-extension-dsl-diagram/src/stores/studio/DiagramEditorState.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/engine/V1_EngineServerClient.ts
Labels: cla-present, Application: Studio, Type: Refactor

#2021 Fix regression introduced for ServiceEditor
  .changeset/early-mayflies-relate.md
  packages/legend-application-studio/src/components/editor/edit-panel/project-configuration-editor/ProjectConfigurationEditor.tsx
  packages/legend-application-studio/style/components/editor/_project-configuration-editor.scss
  packages/legend-art/style/base/_input.scss
Labels: Type: Regression

#2033 fix: creating new query from dataspace
  .changeset/breezy-foxes-mix.md
  packages/legend-extension-dsl-data-space/src/stores/query/DataSpaceQueryCreatorStore.ts
Labels: Type: Bug, Type: Regression, Component: Query Builder

#2037 Fix: allow query ui results to render data for columns with dot notation
  .changeset/debonair-ducks-dwaddle.md
  packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
Labels: Type: Bug, Application: Query

#2005 Save parameter value state when you switch to text mode and back in query builder
  .changeset/sweet-singers-sneeze.md
  .changeset/three-eyes-approve.md
  packages/legend-art/src/testMocks/MonacoEditorMockUtils.tsx
  packages/legend-query-builder/src/components/__tests__/QueryBuilderVariables.test.tsx
  packages/legend-query-builder/src/components/shared/LambdaEditor.tsx
  packages/legend-query-builder/src/stores/QueryBuilderState.ts
  packages/legend-query-builder/src/stores/QueryBuilderStateBuilder.ts
  packages/legend-query-builder/src/stores/milestoning/QueryBuilderMilestoningHelper.ts
Labels: Component: Query Builder

#2039 change scrollbars to lighter color
  .changeset/gracious-grackles-gesture.md
  packages/legend-art/style/base/_normalize.scss
Labels: Component: UX/Design

#1992 Add editors for Trino database connector
  .changeset/sharp-llamas-thank.md
  packages/legend-application-studio/src/components/editor/edit-panel/connection-editor/RelationalDatabaseConnectionEditor.tsx
  packages/legend-application-studio/src/stores/editor/editor-state/element-editor-state/connection/ConnectionEditorState.ts
  packages/legend-application-studio/src/stores/editor/shared/modifier/STO_Relational_GraphModifierHelper.ts
  packages/legend-graph/src/graph/Core_HashUtils.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/relational/connection/AuthenticationStrategy.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/relational/connection/DatasourceSpecification.ts
  packages/legend-graph/src/graph/metamodel/pure/packageableElements/store/relational/connection/RelationalDatabaseConnection.ts
  packages/legend-graph/src/graphManager/action/changeDetection/STO_Relational_ObserverHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/relational/connection/V1_AuthenticationStrategy.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/relational/connection/V1_DatasourceSpecification.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/model/packageableElements/store/relational/connection/V1_RelationalDatabaseConnection.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/from/V1_ConnectionTransformer.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureGraph/to/helpers/V1_RelationalConnectionBuilderHelper.ts
  packages/legend-graph/src/graphManager/protocol/pure/v1/transformation/pureProtocol/serializationHelpers/V1_ConnectionSerializationHelper.ts
  packages/legend-manual-tests/src/__tests__/roundtrip-grammar/cases/STO_Relational-relational-connection-Trino.pure
Labels: Status: Waiting for Backend Change

#2036 Prettify const names with acronyms
  .changeset/flippant-finches-fritter.md
  .changeset/swayed-starlings-shuffle.md
  packages/legend-query-builder/src/components/__tests__/QueryBuilderHighlightExplorerTreeUsedProperty.test.tsx
  packages/legend-shared/src/format/FormatterUtils.ts
  packages/legend-shared/src/format/__tests__/FormatterUtils.test.ts
Labels: Type: Enhancement, Component: UX/Design

#1984 Save query execution results when you switch to text mode and back in query builder
  .changeset/shy-flies-divide.md
  packages/legend-query-builder/src/components/__tests__/QueryBuilderVariables.test.tsx
  packages/legend-query-builder/src/components/shared/LambdaEditor.tsx
  packages/legend-query-builder/src/stores/QueryBuilderState.ts
  packages/legend-query-builder/src/stores/QueryBuilderStateBuilder.ts
  packages/legend-query-builder/src/stores/QueryBuilderTextEditorState.ts
  packages/legend-query-builder/src/stores/__tests__/QueryBuilderResultState.test.ts
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder_ResultStateTest.ts
Labels: cla-present

#1968 Improve ability to use negative numbers in filter & post-filter panel for query builder
  .changeset/common-starling-yodels.md
  .changeset/scrumptious-seagulls-shuffle.md
  .changeset/superb-starlings-scurry.md
  .changeset/young-trains-joke.md
  packages/legend-application-studio/src/stores/editor/NewElementState.ts
  packages/legend-graph/src/graph/MetaModelConst.ts
  packages/legend-query-builder/src/components/QueryBuilderConstantExpressionPanel.tsx
  packages/legend-query-builder/src/components/QueryBuilderResultPanel.tsx
  packages/legend-query-builder/src/components/__tests__/QueryBuilderFetchStructure.test.tsx
  packages/legend-query-builder/src/components/__tests__/QueryBuilderVariables.test.tsx
  packages/legend-query-builder/src/components/shared/BasicValueSpecificationEditor.tsx
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder_Generic.ts
  packages/legend-query-builder/src/stores/__tests__/TEST_DATA__QueryBuilder_Roundtrip_TestFilterQueries.ts
  packages/legend-query-builder/src/stores/fetch-structure/tds/post-filter/QueryBuilderPostFilterStateBuilder.ts
  packages/legend-query-builder/src/stores/filter/QueryBuilderFilterStateBuilder.ts
Labels: cla-present, Application: Query, Component: UX/Design
